DELETE FROM videos WHERE kelas >= 3;

INSERT INTO videos (videoid, title, description, thumbnail, category, subject, kelas) VALUES
-- KELAS 3 SUBJECTS (IPA, IPS, Bahasa Indonesia)
('yt_k3_ipa_01', 'Kelas 3 IPA - Sifat Benda Padat', 'Pembelajaran IPA kelas 3 tentang sifat benda padat', 'https://i.ytimg.com/vi/yt_k3_ipa_01/mqdefault.jpg', 'SD', 'IPA', 3),
('yt_k3_ipa_02', 'Kelas 3 IPA - Sifat Benda Cair', 'Pembelajaran IPA kelas 3 tentang sifat benda cair', 'https://i.ytimg.com/vi/yt_k3_ipa_02/mqdefault.jpg', 'SD', 'IPA', 3),
('yt_k3_ipa_03', 'Kelas 3 IPA - Sifat Benda Gas', 'Pembelajaran IPA kelas 3 tentang sifat benda gas', 'https://i.ytimg.com/vi/yt_k3_ipa_03/mqdefault.jpg', 'SD', 'IPA', 3),
('yt_k3_ipa_04', 'Kelas 3 IPA - Perubahan Wujud Benda', 'Pembelajaran IPA kelas 3 tentang perubahan wujud', 'https://i.ytimg.com/vi/yt_k3_ipa_04/mqdefault.jpg', 'SD', 'IPA', 3),
('yt_k3_ipa_05', 'Kelas 3 IPA - Energi Panas', 'Pembelajaran IPA kelas 3 tentang energi panas', 'https://i.ytimg.com/vi/yt_k3_ipa_05/mqdefault.jpg', 'SD', 'IPA', 3),
('yt_k3_ipa_06', 'Kelas 3 IPA - Energi Cahaya', 'Pembelajaran IPA kelas 3 tentang energi cahaya', 'https://i.ytimg.com/vi/yt_k3_ipa_06/mqdefault.jpg', 'SD', 'IPA', 3),
('yt_k3_ipa_07', 'Kelas 3 IPA - Energi Bunyi', 'Pembelajaran IPA kelas 3 tentang energi bunyi', 'https://i.ytimg.com/vi/yt_k3_ipa_07/mqdefault.jpg', 'SD', 'IPA', 3),
('yt_k3_ipa_08', 'Kelas 3 IPA - Energi Gerak', 'Pembelajaran IPA kelas 3 tentang energi gerak', 'https://i.ytimg.com/vi/yt_k3_ipa_08/mqdefault.jpg', 'SD', 'IPA', 3),
('yt_k3_ipa_09', 'Kelas 3 IPA - Gaya dan Gerak', 'Pembelajaran IPA kelas 3 tentang gaya dan gerak', 'https://i.ytimg.com/vi/yt_k3_ipa_09/mqdefault.jpg', 'SD', 'IPA', 3),
('yt_k3_ipa_10', 'Kelas 3 IPA - Makhluk Hidup', 'Pembelajaran IPA kelas 3 tentang makhluk hidup', 'https://i.ytimg.com/vi/yt_k3_ipa_10/mqdefault.jpg', 'SD', 'IPA', 3),
('yt_k3_ipa_11', 'Kelas 3 IPA - Tumbuhan', 'Pembelajaran IPA kelas 3 tentang tumbuhan', 'https://i.ytimg.com/vi/yt_k3_ipa_11/mqdefault.jpg', 'SD', 'IPA', 3),
('yt_k3_ipa_12', 'Kelas 3 IPA - Hewan', 'Pembelajaran IPA kelas 3 tentang hewan', 'https://i.ytimg.com/vi/yt_k3_ipa_12/mqdefault.jpg', 'SD', 'IPA', 3),
('yt_k3_ipa_13', 'Kelas 3 IPA - Ekosistem', 'Pembelajaran IPA kelas 3 tentang ekosistem', 'https://i.ytimg.com/vi/yt_k3_ipa_13/mqdefault.jpg', 'SD', 'IPA', 3),
('yt_k3_ipa_14', 'Kelas 3 IPA - Rantai Makanan', 'Pembelajaran IPA kelas 3 tentang rantai makanan', 'https://i.ytimg.com/vi/yt_k3_ipa_14/mqdefault.jpg', 'SD', 'IPA', 3),
('yt_k3_ipa_15', 'Kelas 3 IPA - Daur Air', 'Pembelajaran IPA kelas 3 tentang daur air', 'https://i.ytimg.com/vi/yt_k3_ipa_15/mqdefault.jpg', 'SD', 'IPA', 3),
('yt_k3_ipa_16', 'Kelas 3 IPA - Bumi dan Alam Semesta', 'Pembelajaran IPA kelas 3 tentang bumi dan alam semesta', 'https://i.ytimg.com/vi/yt_k3_ipa_16/mqdefault.jpg', 'SD', 'IPA', 3),
('yt_k3_ipa_17', 'Kelas 3 IPA - Cuaca dan Iklim', 'Pembelajaran IPA kelas 3 tentang cuaca dan iklim', 'https://i.ytimg.com/vi/yt_k3_ipa_17/mqdefault.jpg', 'SD', 'IPA', 3),
('yt_k3_ipa_18', 'Kelas 3 IPA - Musim', 'Pembelajaran IPA kelas 3 tentang musim', 'https://i.ytimg.com/vi/yt_k3_ipa_18/mqdefault.jpg', 'SD', 'IPA', 3),
('yt_k3_ipa_19', 'Kelas 3 IPA - Tanah', 'Pembelajaran IPA kelas 3 tentang tanah', 'https://i.ytimg.com/vi/yt_k3_ipa_19/mqdefault.jpg', 'SD', 'IPA', 3),
('yt_k3_ipa_20', 'Kelas 3 IPA - Kesehatan Tubuh', 'Pembelajaran IPA kelas 3 tentang kesehatan tubuh', 'https://i.ytimg.com/vi/yt_k3_ipa_20/mqdefault.jpg', 'SD', 'IPA', 3),

-- KELAS 3 IPS
('yt_k3_ips_01', 'Kelas 3 IPS - Keluarga', 'Pembelajaran IPS kelas 3 tentang keluarga', 'https://i.ytimg.com/vi/yt_k3_ips_01/mqdefault.jpg', 'SD', 'IPS', 3),
('yt_k3_ips_02', 'Kelas 3 IPS - Rumah', 'Pembelajaran IPS kelas 3 tentang rumah', 'https://i.ytimg.com/vi/yt_k3_ips_02/mqdefault.jpg', 'SD', 'IPS', 3),
('yt_k3_ips_03', 'Kelas 3 IPS - Sekolah', 'Pembelajaran IPS kelas 3 tentang sekolah', 'https://i.ytimg.com/vi/yt_k3_ips_03/mqdefault.jpg', 'SD', 'IPS', 3),
('yt_k3_ips_04', 'Kelas 3 IPS - Lingkungan', 'Pembelajaran IPS kelas 3 tentang lingkungan', 'https://i.ytimg.com/vi/yt_k3_ips_04/mqdefault.jpg', 'SD', 'IPS', 3),
('yt_k3_ips_05', 'Kelas 3 IPS - Kampung', 'Pembelajaran IPS kelas 3 tentang kampung', 'https://i.ytimg.com/vi/yt_k3_ips_05/mqdefault.jpg', 'SD', 'IPS', 3),
('yt_k3_ips_06', 'Kelas 3 IPS - Kota', 'Pembelajaran IPS kelas 3 tentang kota', 'https://i.ytimg.com/vi/yt_k3_ips_06/mqdefault.jpg', 'SD', 'IPS', 3),
('yt_k3_ips_07', 'Kelas 3 IPS - Pekerjaan', 'Pembelajaran IPS kelas 3 tentang pekerjaan', 'https://i.ytimg.com/vi/yt_k3_ips_07/mqdefault.jpg', 'SD', 'IPS', 3),
('yt_k3_ips_08', 'Kelas 3 IPS - Transportasi', 'Pembelajaran IPS kelas 3 tentang transportasi', 'https://i.ytimg.com/vi/yt_k3_ips_08/mqdefault.jpg', 'SD', 'IPS', 3),
('yt_k3_ips_09', 'Kelas 3 IPS - Komunikasi', 'Pembelajaran IPS kelas 3 tentang komunikasi', 'https://i.ytimg.com/vi/yt_k3_ips_09/mqdefault.jpg', 'SD', 'IPS', 3),
('yt_k3_ips_10', 'Kelas 3 IPS - Keamanan', 'Pembelajaran IPS kelas 3 tentang keamanan', 'https://i.ytimg.com/vi/yt_k3_ips_10/mqdefault.jpg', 'SD', 'IPS', 3),
('yt_k3_ips_11', 'Kelas 3 IPS - Kesehatan', 'Pembelajaran IPS kelas 3 tentang kesehatan', 'https://i.ytimg.com/vi/yt_k3_ips_11/mqdefault.jpg', 'SD', 'IPS', 3),
('yt_k3_ips_12', 'Kelas 3 IPS - Hiburan', 'Pembelajaran IPS kelas 3 tentang hiburan', 'https://i.ytimg.com/vi/yt_k3_ips_12/mqdefault.jpg', 'SD', 'IPS', 3),
('yt_k3_ips_13', 'Kelas 3 IPS - Budaya Lokal', 'Pembelajaran IPS kelas 3 tentang budaya lokal', 'https://i.ytimg.com/vi/yt_k3_ips_13/mqdefault.jpg', 'SD', 'IPS', 3),
('yt_k3_ips_14', 'Kelas 3 IPS - Seni dan Kerajinan', 'Pembelajaran IPS kelas 3 tentang seni dan kerajinan', 'https://i.ytimg.com/vi/yt_k3_ips_14/mqdefault.jpg', 'SD', 'IPS', 3),
('yt_k3_ips_15', 'Kelas 3 IPS - Tradisi', 'Pembelajaran IPS kelas 3 tentang tradisi', 'https://i.ytimg.com/vi/yt_k3_ips_15/mqdefault.jpg', 'SD', 'IPS', 3),
('yt_k3_ips_16', 'Kelas 3 IPS - Musim Tanam', 'Pembelajaran IPS kelas 3 tentang musim tanam', 'https://i.ytimg.com/vi/yt_k3_ips_16/mqdefault.jpg', 'SD', 'IPS', 3),
('yt_k3_ips_17', 'Kelas 3 IPS - Pertanian', 'Pembelajaran IPS kelas 3 tentang pertanian', 'https://i.ytimg.com/vi/yt_k3_ips_17/mqdefault.jpg', 'SD', 'IPS', 3),
('yt_k3_ips_18', 'Kelas 3 IPS - Perdagangan', 'Pembelajaran IPS kelas 3 tentang perdagangan', 'https://i.ytimg.com/vi/yt_k3_ips_18/mqdefault.jpg', 'SD', 'IPS', 3),
('yt_k3_ips_19', 'Kelas 3 IPS - Pemasaran', 'Pembelajaran IPS kelas 3 tentang pemasaran', 'https://i.ytimg.com/vi/yt_k3_ips_19/mqdefault.jpg', 'SD', 'IPS', 3),
('yt_k3_ips_20', 'Kelas 3 IPS - Ekonomi', 'Pembelajaran IPS kelas 3 tentang ekonomi', 'https://i.ytimg.com/vi/yt_k3_ips_20/mqdefault.jpg', 'SD', 'IPS', 3),

-- KELAS 3 Bahasa Indonesia
('yt_k3_bi_01', 'Kelas 3 Bahasa Indonesia - Membaca', 'Pembelajaran Bahasa Indonesia kelas 3 tentang membaca', 'https://i.ytimg.com/vi/yt_k3_bi_01/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 3),
('yt_k3_bi_02', 'Kelas 3 Bahasa Indonesia - Menulis', 'Pembelajaran Bahasa Indonesia kelas 3 tentang menulis', 'https://i.ytimg.com/vi/yt_k3_bi_02/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 3),
('yt_k3_bi_03', 'Kelas 3 Bahasa Indonesia - Berbicara', 'Pembelajaran Bahasa Indonesia kelas 3 tentang berbicara', 'https://i.ytimg.com/vi/yt_k3_bi_03/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 3),
('yt_k3_bi_04', 'Kelas 3 Bahasa Indonesia - Mendengarkan', 'Pembelajaran Bahasa Indonesia kelas 3 tentang mendengarkan', 'https://i.ytimg.com/vi/yt_k3_bi_04/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 3),
('yt_k3_bi_05', 'Kelas 3 Bahasa Indonesia - Huruf', 'Pembelajaran Bahasa Indonesia kelas 3 tentang huruf', 'https://i.ytimg.com/vi/yt_k3_bi_05/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 3),
('yt_k3_bi_06', 'Kelas 3 Bahasa Indonesia - Suku Kata', 'Pembelajaran Bahasa Indonesia kelas 3 tentang suku kata', 'https://i.ytimg.com/vi/yt_k3_bi_06/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 3),
('yt_k3_bi_07', 'Kelas 3 Bahasa Indonesia - Kata', 'Pembelajaran Bahasa Indonesia kelas 3 tentang kata', 'https://i.ytimg.com/vi/yt_k3_bi_07/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 3),
('yt_k3_bi_08', 'Kelas 3 Bahasa Indonesia - Kalimat', 'Pembelajaran Bahasa Indonesia kelas 3 tentang kalimat', 'https://i.ytimg.com/vi/yt_k3_bi_08/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 3),
('yt_k3_bi_09', 'Kelas 3 Bahasa Indonesia - Cerita', 'Pembelajaran Bahasa Indonesia kelas 3 tentang cerita', 'https://i.ytimg.com/vi/yt_k3_bi_09/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 3),
('yt_k3_bi_10', 'Kelas 3 Bahasa Indonesia - Puisi', 'Pembelajaran Bahasa Indonesia kelas 3 tentang puisi', 'https://i.ytimg.com/vi/yt_k3_bi_10/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 3),
('yt_k3_bi_11', 'Kelas 3 Bahasa Indonesia - Pantun', 'Pembelajaran Bahasa Indonesia kelas 3 tentang pantun', 'https://i.ytimg.com/vi/yt_k3_bi_11/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 3),
('yt_k3_bi_12', 'Kelas 3 Bahasa Indonesia - Syair', 'Pembelajaran Bahasa Indonesia kelas 3 tentang syair', 'https://i.ytimg.com/vi/yt_k3_bi_12/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 3),
('yt_k3_bi_13', 'Kelas 3 Bahasa Indonesia - Drama', 'Pembelajaran Bahasa Indonesia kelas 3 tentang drama', 'https://i.ytimg.com/vi/yt_k3_bi_13/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 3),
('yt_k3_bi_14', 'Kelas 3 Bahasa Indonesia - Dialog', 'Pembelajaran Bahasa Indonesia kelas 3 tentang dialog', 'https://i.ytimg.com/vi/yt_k3_bi_14/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 3),
('yt_k3_bi_15', 'Kelas 3 Bahasa Indonesia - Teks Informatif', 'Pembelajaran Bahasa Indonesia kelas 3 tentang teks informatif', 'https://i.ytimg.com/vi/yt_k3_bi_15/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 3),
('yt_k3_bi_16', 'Kelas 3 Bahasa Indonesia - Teks Deskriptif', 'Pembelajaran Bahasa Indonesia kelas 3 tentang teks deskriptif', 'https://i.ytimg.com/vi/yt_k3_bi_16/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 3),
('yt_k3_bi_17', 'Kelas 3 Bahasa Indonesia - Teks Naratif', 'Pembelajaran Bahasa Indonesia kelas 3 tentang teks naratif', 'https://i.ytimg.com/vi/yt_k3_bi_17/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 3),
('yt_k3_bi_18', 'Kelas 3 Bahasa Indonesia - Teks Eksplanatif', 'Pembelajaran Bahasa Indonesia kelas 3 tentang teks eksplanatif', 'https://i.ytimg.com/vi/yt_k3_bi_18/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 3),
('yt_k3_bi_19', 'Kelas 3 Bahasa Indonesia - Teks Persuasif', 'Pembelajaran Bahasa Indonesia kelas 3 tentang teks persuasif', 'https://i.ytimg.com/vi/yt_k3_bi_19/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 3),
('yt_k3_bi_20', 'Kelas 3 Bahasa Indonesia - Teks Prosedur', 'Pembelajaran Bahasa Indonesia kelas 3 tentang teks prosedur', 'https://i.ytimg.com/vi/yt_k3_bi_20/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 3);
