DELETE FROM videos WHERE kelas >= 5;

INSERT INTO videos (videoid, title, description, thumbnail, category, subject, kelas) VALUES
-- KELAS 5-6 SUBJECTS (5 subjects × 20 videos each)
('yt_k5_ipa_01', 'Kelas 5 IPA - Sifat Benda Padat', 'Pembelajaran IPA kelas 5 tentang sifat benda padat', 'https://i.ytimg.com/vi/yt_k5_ipa_01/mqdefault.jpg', 'SD', 'IPA', 5),
('yt_k3_ipa_02', 'Kelas 3 IPA - Sifat Benda Cair', 'Pembelajaran IPA kelas 3 tentang sifat benda cair', 'https://i.ytimg.com/vi/yt_k3_ipa_02/mqdefault.jpg', 'SD', 'IPA', 3),
('yt_k3_ipa_03', 'Kelas 3 IPA - Sifat Benda Gas', 'Pembelajaran IPA kelas 3 tentang sifat benda gas', 'https://i.ytimg.com/vi/yt_k3_ipa_03/mqdefault.jpg', 'SD', 'IPA', 3),
('yt_k3_ipa_04', 'Kelas 3 IPA - Perubahan Wujud Benda', 'Pembelajaran IPA kelas 3 tentang perubahan wujud', 'https://i.ytimg.com/vi/yt_k3_ipa_04/mqdefault.jpg', 'SD', 'IPA', 3),
('yt_k3_ipa_05', 'Kelas 3 IPA - Energi Panas', 'Pembelajaran IPA kelas 3 tentang energi panas', 'https://i.ytimg.com/vi/yt_k3_ipa_05/mqdefault.jpg', 'SD', 'IPA', 3),
('yt_k3_ipa_06', 'Kelas 3 IPA - Energi Cahaya', 'Pembelajaran IPA kelas 3 tentang energi cahaya', 'https://i.ytimg.com/vi/yt_k3_ipa_06/mqdefault.jpg', 'SD', 'IPA', 3),
('yt_k3_ipa_07', 'Kelas 3 IPA - Energi Bunyi', 'Pembelajaran IPA kelas 3 tentang energi bunyi', 'https://i.ytimg.com/vi/yt_k3_ipa_07/mqdefault.jpg', 'SD', 'IPA', 3),
('yt_k3_ipa_08', 'Kelas 3 IPA - Energi Gerak', 'Pembelajaran IPA kelas 3 tentang energi gerak', 'https://i.ytimg.com/vi/yt_k3_ipa_08/mqdefault.jpg', 'SD', 'IPA', 3),
('yt_k3_ipa_09', 'Kelas 3 IPA - Gaya dan Gerak', 'Pembelajaran IPA kelas 3 tentang gaya dan gerak', 'https://i.ytimg.com/vi/yt_k3_ipa_09/mqdefault.jpg', 'SD', 'IPA', 3),
('yt_k3_ipa_10', 'Kelas 3 IPA - Makhluk Hidup', 'Pembelajaran IPA kelas 3 tentang makhluk hidup', 'https://i.ytimg.com/vi/yt_k3_ipa_10/mqdefault.jpg', 'SD', 'IPA', 3),
('yt_k3_ipa_11', 'Kelas 3 IPA - Tumbuhan', 'Pembelajaran IPA kelas 3 tentang tumbuhan', 'https://i.ytimg.com/vi/yt_k3_ipa_11/mqdefault.jpg', 'SD', 'IPA', 3),
('yt_k3_ipa_12', 'Kelas 3 IPA - Hewan', 'Pembelajaran IPA kelas 3 tentang hewan', 'https://i.ytimg.com/vi/yt_k3_ipa_12/mqdefault.jpg', 'SD', 'IPA', 3),
('yt_k3_ipa_13', 'Kelas 3 IPA - Ekosistem', 'Pembelajaran IPA kelas 3 tentang ekosistem', 'https://i.ytimg.com/vi/yt_k3_ipa_13/mqdefault.jpg', 'SD', 'IPA', 3),
('yt_k3_ipa_14', 'Kelas 3 IPA - Rantai Makanan', 'Pembelajaran IPA kelas 3 tentang rantai makanan', 'https://i.ytimg.com/vi/yt_k3_ipa_14/mqdefault.jpg', 'SD', 'IPA', 3),
('yt_k3_ipa_15', 'Kelas 3 IPA - Daur Air', 'Pembelajaran IPA kelas 3 tentang daur air', 'https://i.ytimg.com/vi/yt_k3_ipa_15/mqdefault.jpg', 'SD', 'IPA', 3),
('yt_k3_ipa_16', 'Kelas 3 IPA - Bumi dan Alam Semesta', 'Pembelajaran IPA kelas 3 tentang bumi dan alam semesta', 'https://i.ytimg.com/vi/yt_k3_ipa_16/mqdefault.jpg', 'SD', 'IPA', 3),
('yt_k3_ipa_17', 'Kelas 3 IPA - Cuaca dan Iklim', 'Pembelajaran IPA kelas 3 tentang cuaca dan iklim', 'https://i.ytimg.com/vi/yt_k3_ipa_17/mqdefault.jpg', 'SD', 'IPA', 3),
('yt_k3_ipa_18', 'Kelas 3 IPA - Musim', 'Pembelajaran IPA kelas 3 tentang musim', 'https://i.ytimg.com/vi/yt_k3_ipa_18/mqdefault.jpg', 'SD', 'IPA', 3),
('yt_k3_ipa_19', 'Kelas 3 IPA - Tanah', 'Pembelajaran IPA kelas 3 tentang tanah', 'https://i.ytimg.com/vi/yt_k3_ipa_19/mqdefault.jpg', 'SD', 'IPA', 3),
('yt_k3_ipa_20', 'Kelas 3 IPA - Kesehatan Tubuh', 'Pembelajaran IPA kelas 3 tentang kesehatan tubuh', 'https://i.ytimg.com/vi/yt_k3_ipa_20/mqdefault.jpg', 'SD', 'IPA', 3),

-- KELAS 7-9 SUBJECTS (6 subjects × 20 videos each)
('yt_k3_ips_01', 'Kelas 3 IPS - Keluarga', 'Pembelajaran IPS kelas 3 tentang keluarga', 'https://i.ytimg.com/vi/yt_k3_ips_01/mqdefault.jpg', 'SD', 'IPS', 3),
('yt_k3_ips_02', 'Kelas 3 IPS - Rumah', 'Pembelajaran IPS kelas 3 tentang rumah', 'https://i.ytimg.com/vi/yt_k3_ips_02/mqdefault.jpg', 'SD', 'IPS', 3),
('yt_k3_ips_03', 'Kelas 3 IPS - Sekolah', 'Pembelajaran IPS kelas 3 tentang sekolah', 'https://i.ytimg.com/vi/yt_k3_ips_03/mqdefault.jpg', 'SD', 'IPS', 3),
('yt_k3_ips_04', 'Kelas 3 IPS - Lingkungan', 'Pembelajaran IPS kelas 3 tentang lingkungan', 'https://i.ytimg.com/vi/yt_k3_ips_04/mqdefault.jpg', 'SD', 'IPS', 3),
('yt_k3_ips_05', 'Kelas 3 IPS - Kampung', 'Pembelajaran IPS kelas 3 tentang kampung', 'https://i.ytimg.com/vi/yt_k3_ips_05/mqdefault.jpg', 'SD', 'IPS', 3),
('yt_k3_ips_06', 'Kelas 3 IPS - Kota', 'Pembelajaran IPS kelas 3 tentang kota', 'https://i.ytimg.com/vi/yt_k3_ips_06/mqdefault.jpg', 'SD', 'IPS', 3),
('yt_k3_ips_07', 'Kelas 3 IPS - Pekerjaan', 'Pembelajaran IPS kelas 3 tentang pekerjaan', 'https://i.ytimg.com/vi/yt_k3_ips_07/mqdefault.jpg', 'SD', 'IPS', 3),
('yt_k3_ips_08', 'Kelas 3 IPS - Transportasi', 'Pembelajaran IPS kelas 3 tentang transportasi', 'https://i.ytimg.com/vi/yt_k3_ips_08/mqdefault.jpg', 'SD', 'IPS', 3),
('yt_k3_ips_09', 'Kelas 3 IPS - Komunikasi', 'Pembelajaran IPS kelas 3 tentang komunikasi', 'https://i.ytimg.com/vi/yt_k3_ips_09/mqdefault.jpg', 'SD', 'IPS', 3),
('yt_k3_ips_10', 'Kelas 3 IPS - Keamanan', 'Pembelajaran IPS kelas 3 tentang keamanan', 'https://i.ytimg.com/vi/yt_k3_ips_10/mqdefault.jpg', 'SD', 'IPS', 3),
('yt_k3_ips_11', 'Kelas 3 IPS - Kesehatan', 'Pembelajaran IPS kelas 3 tentang kesehatan', 'https://i.ytimg.com/vi/yt_k3_ips_11/mqdefault.jpg', 'SD', 'IPS', 3),
('yt_k3_ips_12', 'Kelas 3 IPS - Hiburan', 'Pembelajaran IPS kelas 3 tentang hiburan', 'https://i.ytimg.com/vi/yt_k3_ips_12/mqdefault.jpg', 'SD', 'IPS', 3),
('yt_k3_ips_13', 'Kelas 3 IPS - Budaya Lokal', 'Pembelajaran IPS kelas 3 tentang budaya lokal', 'https://i.ytimg.com/vi/yt_k3_ips_13/mqdefault.jpg', 'SD', 'IPS', 3),
('yt_k3_ips_14', 'Kelas 3 IPS - Seni dan Kerajinan', 'Pembelajaran IPS kelas 3 tentang seni dan kerajinan', 'https://i.ytimg.com/vi/yt_k3_ips_14/mqdefault.jpg', 'SD', 'IPS', 3),
('yt_k3_ips_15', 'Kelas 3 IPS - Tradisi', 'Pembelajaran IPS kelas 3 tentang tradisi', 'https://i.ytimg.com/vi/yt_k3_ips_15/mqdefault.jpg', 'SD', 'IPS', 3),
('yt_k3_ips_16', 'Kelas 3 IPS - Musim Tanam', 'Pembelajaran IPS kelas 3 tentang musim tanam', 'https://i.ytimg.com/vi/yt_k3_ips_16/mqdefault.jpg', 'SD', 'IPS', 3),
('yt_k3_ips_17', 'Kelas 3 IPS - Pertanian', 'Pembelajaran IPS kelas 3 tentang pertanian', 'https://i.ytimg.com/vi/yt_k3_ips_17/mqdefault.jpg', 'SD', 'IPS', 3),
('yt_k3_ips_18', 'Kelas 3 IPS - Perdagangan', 'Pembelajaran IPS kelas 3 tentang perdagangan', 'https://i.ytimg.com/vi/yt_k3_ips_18/mqdefault.jpg', 'SD', 'IPS', 3),
('yt_k3_ips_19', 'Kelas 3 IPS - Pemasaran', 'Pembelajaran IPS kelas 3 tentang pemasaran', 'https://i.ytimg.com/vi/yt_k3_ips_19/mqdefault.jpg', 'SD', 'IPS', 3),
('yt_k3_ips_20', 'Kelas 3 IPS - Ekonomi', 'Pembelajaran IPS kelas 3 tentang ekonomi', 'https://i.ytimg.com/vi/yt_k3_ips_20/mqdefault.jpg', 'SD', 'IPS', 3),

-- KELAS 10-12 Bahasa Indonesia
('yt_k3_bi_01', 'Kelas 3 Bahasa Indonesia - Membaca', 'Pembelajaran Bahasa Indonesia kelas 3 tentang membaca', 'https://i.ytimg.com/vi/yt_k3_bi_01/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 3),
('yt_k3_bi_02', 'Kelas 3 Bahasa Indonesia - Menulis', 'Pembelajaran Bahasa Indonesia kelas 3 tentang menulis', 'https://i.ytimg.com/vi/yt_k3_bi_02/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 3),
('yt_k3_bi_03', 'Kelas 3 Bahasa Indonesia - Berbicara', 'Pembelajaran Bahasa Indonesia kelas 3 tentang berbicara', 'https://i.ytimg.com/vi/yt_k3_bi_03/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 3),
('yt_k3_bi_04', 'Kelas 3 Bahasa Indonesia - Mendengarkan', 'Pembelajaran Bahasa Indonesia kelas 3 tentang mendengarkan', 'https://i.ytimg.com/vi/yt_k3_bi_04/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 3),
('yt_k3_bi_05', 'Kelas 3 Bahasa Indonesia - Huruf', 'Pembelajaran Bahasa Indonesia kelas 3 tentang huruf', 'https://i.ytimg.com/vi/yt_k3_bi_05/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 3),
('yt_k3_bi_06', 'Kelas 3 Bahasa Indonesia - Suku Kata', 'Pembelajaran Bahasa Indonesia kelas 3 tentang suku kata', 'https://i.ytimg.com/vi/yt_k3_bi_06/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 3),
('yt_k3_bi_07', 'Kelas 3 Bahasa Indonesia - Kata', 'Pembelajaran Bahasa Indonesia kelas 3 tentang kata', 'https://i.ytimg.com/vi/yt_k3_bi_07/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 3),
('yt_k3_bi_08', 'Kelas 3 Bahasa Indonesia - Kalimat', 'Pembelajaran Bahasa Indonesia kelas 3 tentang kalimat', 'https://i.ytimg.com/vi/yt_k3_bi_08/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 3),
('yt_k3_bi_09', 'Kelas 3 Bahasa Indonesia - Cerita', 'Pembelajaran Bahasa Indonesia kelas 3 tentang cerita', 'https://i.ytimg.com/vi/yt_k3_bi_09/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 3),
('yt_k3_bi_10', 'Kelas 3 Bahasa Indonesia - Puisi', 'Pembelajaran Bahasa Indonesia kelas 3 tentang puisi', 'https://i.ytimg.com/vi/yt_k3_bi_10/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 3),
('yt_k3_bi_11', 'Kelas 3 Bahasa Indonesia - Pantun', 'Pembelajaran Bahasa Indonesia kelas 3 tentang pantun', 'https://i.ytimg.com/vi/yt_k3_bi_11/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 3),
('yt_k3_bi_12', 'Kelas 3 Bahasa Indonesia - Syair', 'Pembelajaran Bahasa Indonesia kelas 3 tentang syair', 'https://i.ytimg.com/vi/yt_k3_bi_12/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 3),
('yt_k3_bi_13', 'Kelas 3 Bahasa Indonesia - Drama', 'Pembelajaran Bahasa Indonesia kelas 3 tentang drama', 'https://i.ytimg.com/vi/yt_k3_bi_13/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 3),
('yt_k3_bi_14', 'Kelas 3 Bahasa Indonesia - Dialog', 'Pembelajaran Bahasa Indonesia kelas 3 tentang dialog', 'https://i.ytimg.com/vi/yt_k3_bi_14/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 3),
('yt_k3_bi_15', 'Kelas 3 Bahasa Indonesia - Teks Informatif', 'Pembelajaran Bahasa Indonesia kelas 3 tentang teks informatif', 'https://i.ytimg.com/vi/yt_k3_bi_15/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 3),
('yt_k3_bi_16', 'Kelas 3 Bahasa Indonesia - Teks Deskriptif', 'Pembelajaran Bahasa Indonesia kelas 3 tentang teks deskriptif', 'https://i.ytimg.com/vi/yt_k3_bi_16/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 3),
('yt_k3_bi_17', 'Kelas 3 Bahasa Indonesia - Teks Naratif', 'Pembelajaran Bahasa Indonesia kelas 3 tentang teks naratif', 'https://i.ytimg.com/vi/yt_k3_bi_17/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 3),
('yt_k3_bi_18', 'Kelas 3 Bahasa Indonesia - Teks Eksplanatif', 'Pembelajaran Bahasa Indonesia kelas 3 tentang teks eksplanatif', 'https://i.ytimg.com/vi/yt_k3_bi_18/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 3),
('yt_k3_bi_19', 'Kelas 3 Bahasa Indonesia - Teks Persuasif', 'Pembelajaran Bahasa Indonesia kelas 3 tentang teks persuasif', 'https://i.ytimg.com/vi/yt_k3_bi_19/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 3),
('yt_k3_bi_20', 'Kelas 3 Bahasa Indonesia - Teks Prosedur', 'Pembelajaran Bahasa Indonesia kelas 3 tentang teks prosedur', 'https://i.ytimg.com/vi/yt_k3_bi_20/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 3),

-- KELAS 4-6 DATA (Adding Bahasa Inggris)
-- KELAS 4 MATEMATIKA
('yt_k4_mat_01', 'Kelas 4 Matematika - Bilangan Bulat', 'Pembelajaran Matematika kelas 4 tentang bilangan bulat', 'https://i.ytimg.com/vi/yt_k4_mat_01/mqdefault.jpg', 'SD', 'Matematika', 4),
('yt_k4_mat_02', 'Kelas 4 Matematika - Operasi Hitung', 'Pembelajaran Matematika kelas 4 tentang operasi hitung', 'https://i.ytimg.com/vi/yt_k4_mat_02/mqdefault.jpg', 'SD', 'Matematika', 4),
('yt_k4_mat_03', 'Kelas 4 Matematika - FPB dan KPK', 'Pembelajaran Matematika kelas 4 tentang FPB dan KPK', 'https://i.ytimg.com/vi/yt_k4_mat_03/mqdefault.jpg', 'SD', 'Matematika', 4),
('yt_k4_mat_04', 'Kelas 4 Matematika - Pecahan', 'Pembelajaran Matematika kelas 4 tentang pecahan', 'https://i.ytimg.com/vi/yt_k4_mat_04/mqdefault.jpg', 'SD', 'Matematika', 4),
('yt_k4_mat_05', 'Kelas 4 Matematika - Desimal', 'Pembelajaran Matematika kelas 4 tentang desimal', 'https://i.ytimg.com/vi/yt_k4_mat_05/mqdefault.jpg', 'SD', 'Matematika', 4),
('yt_k4_mat_06', 'Kelas 4 Matematika - Persentase', 'Pembelajaran Matematika kelas 4 tentang persentase', 'https://i.ytimg.com/vi/yt_k4_mat_06/mqdefault.jpg', 'SD', 'Matematika', 4),
('yt_k4_mat_07', 'Kelas 4 Matematika - Satuan Panjang', 'Pembelajaran Matematika kelas 4 tentang satuan panjang', 'https://i.ytimg.com/vi/yt_k4_mat_07/mqdefault.jpg', 'SD', 'Matematika', 4),
('yt_k4_mat_08', 'Kelas 4 Matematika - Satuan Berat', 'Pembelajaran Matematika kelas 4 tentang satuan berat', 'https://i.ytimg.com/vi/yt_k4_mat_08/mqdefault.jpg', 'SD', 'Matematika', 4),
('yt_k4_mat_09', 'Kelas 4 Matematika - Satuan Waktu', 'Pembelajaran Matematika kelas 4 tentang satuan waktu', 'https://i.ytimg.com/vi/yt_k4_mat_09/mqdefault.jpg', 'SD', 'Matematika', 4),
('yt_k4_mat_10', 'Kelas 4 Matematika - Satuan Suhu', 'Pembelajaran Matematika kelas 4 tentang satuan suhu', 'https://i.ytimg.com/vi/yt_k4_mat_10/mqdefault.jpg', 'SD', 'Matematika', 4),
('yt_k4_mat_11', 'Kelas 4 Matematika - Keliling Bangun Datar', 'Pembelajaran Matematika kelas 4 tentang keliling bangun datar', 'https://i.ytimg.com/vi/yt_k4_mat_11/mqdefault.jpg', 'SD', 'Matematika', 4),
('yt_k4_mat_12', 'Kelas 4 Matematika - Luas Bangun Datar', 'Pembelajaran Matematika kelas 4 tentang luas bangun datar', 'https://i.ytimg.com/vi/yt_k4_mat_12/mqdefault.jpg', 'SD', 'Matematika', 4),
('yt_k4_mat_13', 'Kelas 4 Matematika - Bangun Ruang', 'Pembelajaran Matematika kelas 4 tentang bangun ruang', 'https://i.ytimg.com/vi/yt_k4_mat_13/mqdefault.jpg', 'SD', 'Matematika', 4),
('yt_k4_mat_14', 'Kelas 4 Matematika - Volume Bangun Ruang', 'Pembelajaran Matematika kelas 4 tentang volume bangun ruang', 'https://i.ytimg.com/vi/yt_k4_mat_14/mqdefault.jpg', 'SD', 'Matematika', 4),
('yt_k4_mat_15', 'Kelas 4 Matematika - Koordinat Kartesius', 'Pembelajaran Matematika kelas 4 tentang koordinat kartesius', 'https://i.ytimg.com/vi/yt_k4_mat_15/mqdefault.jpg', 'SD', 'Matematika', 4),
('yt_k4_mat_16', 'Kelas 4 Matematika - Data dan Statistik', 'Pembelajaran Matematika kelas 4 tentang data dan statistik', 'https://i.ytimg.com/vi/yt_k4_mat_16/mqdefault.jpg', 'SD', 'Matematika', 4),
('yt_k4_mat_17', 'Kelas 4 Matematika - Rata-rata', 'Pembelajaran Matematika kelas 4 tentang rata-rata', 'https://i.ytimg.com/vi/yt_k4_mat_17/mqdefault.jpg', 'SD', 'Matematika', 4),
('yt_k4_mat_18', 'Kelas 4 Matematika - Modus', 'Pembelajaran Matematika kelas 4 tentang modus', 'https://i.ytimg.com/vi/yt_k4_mat_18/mqdefault.jpg', 'SD', 'Matematika', 4),
('yt_k4_mat_19', 'Kelas 4 Matematika - Median', 'Pembelajaran Matematika kelas 4 tentang median', 'https://i.ytimg.com/vi/yt_k4_mat_19/mqdefault.jpg', 'SD', 'Matematika', 4),
('yt_k4_mat_20', 'Kelas 4 Matematika - Diagram Batang', 'Pembelajaran Matematika kelas 4 tentang diagram batang', 'https://i.ytimg.com/vi/yt_k4_mat_20/mqdefault.jpg', 'SD', 'Matematika', 4),

-- KELAS 4 IPA
('yt_k4_ipa_01', 'Kelas 4 IPA - Struktur Tumbuhan', 'Pembelajaran IPA kelas 4 tentang struktur tumbuhan', 'https://i.ytimg.com/vi/yt_k4_ipa_01/mqdefault.jpg', 'SD', 'IPA', 4),
('yt_k4_ipa_02', 'Kelas 4 IPA - Fungsi Tumbuhan', 'Pembelajaran IPA kelas 4 tentang fungsi tumbuhan', 'https://i.ytimg.com/vi/yt_k4_ipa_02/mqdefault.jpg', 'SD', 'IPA', 4),
('yt_k4_ipa_03', 'Kelas 4 IPA - Fotosintesis', 'Pembelajaran IPA kelas 4 tentang fotosintesis', 'https://i.ytimg.com/vi/yt_k4_ipa_03/mqdefault.jpg', 'SD', 'IPA', 4),
('yt_k4_ipa_04', 'Kelas 4 IPA - Struktur Hewan', 'Pembelajaran IPA kelas 4 tentang struktur hewan', 'https://i.ytimg.com/vi/yt_k4_ipa_04/mqdefault.jpg', 'SD', 'IPA', 4),
('yt_k4_ipa_05', 'Kelas 4 IPA - Fungsi Hewan', 'Pembelajaran IPA kelas 4 tentang fungsi hewan', 'https://i.ytimg.com/vi/yt_k4_ipa_05/mqdefault.jpg', 'SD', 'IPA', 4),
('yt_k4_ipa_06', 'Kelas 4 IPA - Organ Tubuh Manusia', 'Pembelajaran IPA kelas 4 tentang organ tubuh manusia', 'https://i.ytimg.com/vi/yt_k4_ipa_06/mqdefault.jpg', 'SD', 'IPA', 4),
('yt_k4_ipa_07', 'Kelas 4 IPA - Sistem Pencernaan', 'Pembelajaran IPA kelas 4 tentang sistem pencernaan', 'https://i.ytimg.com/vi/yt_k4_ipa_07/mqdefault.jpg', 'SD', 'IPA', 4),
('yt_k4_ipa_08', 'Kelas 4 IPA - Sistem Peredaran Darah', 'Pembelajaran IPA kelas 4 tentang sistem peredaran darah', 'https://i.ytimg.com/vi/yt_k4_ipa_08/mqdefault.jpg', 'SD', 'IPA', 4),
('yt_k4_ipa_09', 'Kelas 4 IPA - Sistem Pernapasan', 'Pembelajaran IPA kelas 4 tentang sistem pernapasan', 'https://i.ytimg.com/vi/yt_k4_ipa_09/mqdefault.jpg', 'SD', 'IPA', 4),
('yt_k4_ipa_10', 'Kelas 4 IPA - Sistem Saraf', 'Pembelajaran IPA kelas 4 tentang sistem saraf', 'https://i.ytimg.com/vi/yt_k4_ipa_10/mqdefault.jpg', 'SD', 'IPA', 4),
('yt_k4_ipa_11', 'Kelas 4 IPA - Indera Manusia', 'Pembelajaran IPA kelas 4 tentang indera manusia', 'https://i.ytimg.com/vi/yt_k4_ipa_11/mqdefault.jpg', 'SD', 'IPA', 4),
('yt_k4_ipa_12', 'Kelas 4 IPA - Kesehatan Pribadi', 'Pembelajaran IPA kelas 4 tentang kesehatan pribadi', 'https://i.ytimg.com/vi/yt_k4_ipa_12/mqdefault.jpg', 'SD', 'IPA', 4),
('yt_k4_ipa_13', 'Kelas 4 IPA - Penyakit Menular', 'Pembelajaran IPA kelas 4 tentang penyakit menular', 'https://i.ytimg.com/vi/yt_k4_ipa_13/mqdefault.jpg', 'SD', 'IPA', 4),
('yt_k4_ipa_14', 'Kelas 4 IPA - Makanan Bergizi', 'Pembelajaran IPA kelas 4 tentang makanan bergizi', 'https://i.ytimg.com/vi/yt_k4_ipa_14/mqdefault.jpg', 'SD', 'IPA', 4),
('yt_k4_ipa_15', 'Kelas 4 IPA - Olahraga', 'Pembelajaran IPA kelas 4 tentang olahraga', 'https://i.ytimg.com/vi/yt_k4_ipa_15/mqdefault.jpg', 'SD', 'IPA', 4),
('yt_k4_ipa_16', 'Kelas 4 IPA - Penjernihan Air', 'Pembelajaran IPA kelas 4 tentang penjernihan air', 'https://i.ytimg.com/vi/yt_k4_ipa_16/mqdefault.jpg', 'SD', 'IPA', 4),
('yt_k4_ipa_17', 'Kelas 4 IPA - Pencemaran Lingkungan', 'Pembelajaran IPA kelas 4 tentang pencemaran lingkungan', 'https://i.ytimg.com/vi/yt_k4_ipa_17/mqdefault.jpg', 'SD', 'IPA', 4),
('yt_k4_ipa_18', 'Kelas 4 IPA - Energi Terbarukan', 'Pembelajaran IPA kelas 4 tentang energi terbarukan', 'https://i.ytimg.com/vi/yt_k4_ipa_18/mqdefault.jpg', 'SD', 'IPA', 4),
('yt_k4_ipa_19', 'Kelas 4 IPA - Magnet', 'Pembelajaran IPA kelas 4 tentang magnet', 'https://i.ytimg.com/vi/yt_k4_ipa_19/mqdefault.jpg', 'SD', 'IPA', 4),
('yt_k4_ipa_20', 'Kelas 4 IPA - Gelombang', 'Pembelajaran IPA kelas 4 tentang gelombang', 'https://i.ytimg.com/vi/yt_k4_ipa_20/mqdefault.jpg', 'SD', 'IPA', 4),

-- KELAS 4 IPS
('yt_k4_ips_01', 'Kelas 4 IPS - Pemerintahan', 'Pembelajaran IPS kelas 4 tentang pemerintahan', 'https://i.ytimg.com/vi/yt_k4_ips_01/mqdefault.jpg', 'SD', 'IPS', 4),
('yt_k4_ips_02', 'Kelas 4 IPS - Hak dan Kewajiban', 'Pembelajaran IPS kelas 4 tentang hak dan kewajiban', 'https://i.ytimg.com/vi/yt_k4_ips_02/mqdefault.jpg', 'SD', 'IPS', 4),
('yt_k4_ips_03', 'Kelas 4 IPS - Pancasila', 'Pembelajaran IPS kelas 4 tentang Pancasila', 'https://i.ytimg.com/vi/yt_k4_ips_03/mqdefault.jpg', 'SD', 'IPS', 4),
('yt_k4_ips_04', 'Kelas 4 IPS - UUD 1945', 'Pembelajaran IPS kelas 4 tentang UUD 1945', 'https://i.ytimg.com/vi/yt_k4_ips_04/mqdefault.jpg', 'SD', 'IPS', 4),
('yt_k4_ips_05', 'Kelas 4 IPS - Kehidupan Sosial', 'Pembelajaran IPS kelas 4 tentang kehidupan sosial', 'https://i.ytimg.com/vi/yt_k4_ips_05/mqdefault.jpg', 'SD', 'IPS', 4),
('yt_k4_ips_06', 'Kelas 4 IPS - Keberagaman Budaya', 'Pembelajaran IPS kelas 4 tentang keberagaman budaya', 'https://i.ytimg.com/vi/yt_k4_ips_06/mqdefault.jpg', 'SD', 'IPS', 4),
('yt_k4_ips_07', 'Kelas 4 IPS - Bahasa Daerah', 'Pembelajaran IPS kelas 4 tentang bahasa daerah', 'https://i.ytimg.com/vi/yt_k4_ips_07/mqdefault.jpg', 'SD', 'IPS', 4),
('yt_k4_ips_08', 'Kelas 4 IPS - Seni Tradisional', 'Pembelajaran IPS kelas 4 tentang seni tradisional', 'https://i.ytimg.com/vi/yt_k4_ips_08/mqdefault.jpg', 'SD', 'IPS', 4),
('yt_k4_ips_09', 'Kelas 4 IPS - Pakaian Tradisional', 'Pembelajaran IPS kelas 4 tentang pakaian tradisional', 'https://i.ytimg.com/vi/yt_k4_ips_09/mqdefault.jpg', 'SD', 'IPS', 4),
('yt_k4_ips_10', 'Kelas 4 IPS - Makanan Tradisional', 'Pembelajaran IPS kelas 4 tentang makanan tradisional', 'https://i.ytimg.com/vi/yt_k4_ips_10/mqdefault.jpg', 'SD', 'IPS', 4),
('yt_k4_ips_11', 'Kelas 4 IPS - Rumah Tradisional', 'Pembelajaran IPS kelas 4 tentang rumah tradisional', 'https://i.ytimg.com/vi/yt_k4_ips_11/mqdefault.jpg', 'SD', 'IPS', 4),
('yt_k4_ips_12', 'Kelas 4 IPS - Upacara Tradisional', 'Pembelajaran IPS kelas 4 tentang upacara tradisional', 'https://i.ytimg.com/vi/yt_k4_ips_12/mqdefault.jpg', 'SD', 'IPS', 4),
('yt_k4_ips_13', 'Kelas 4 IPS - Permainan Tradisional', 'Pembelajaran IPS kelas 4 tentang permainan tradisional', 'https://i.ytimg.com/vi/yt_k4_ips_13/mqdefault.jpg', 'SD', 'IPS', 4),
('yt_k4_ips_14', 'Kelas 4 IPS - Pertanian Indonesia', 'Pembelajaran IPS kelas 4 tentang pertanian Indonesia', 'https://i.ytimg.com/vi/yt_k4_ips_14/mqdefault.jpg', 'SD', 'IPS', 4),
('yt_k4_ips_15', 'Kelas 4 IPS - Perikanan Indonesia', 'Pembelajaran IPS kelas 4 tentang perikanan Indonesia', 'https://i.ytimg.com/vi/yt_k4_ips_15/mqdefault.jpg', 'SD', 'IPS', 4),
('yt_k4_ips_16', 'Kelas 4 IPS - Pertambangan Indonesia', 'Pembelajaran IPS kelas 4 tentang pertambangan Indonesia', 'https://i.ytimg.com/vi/yt_k4_ips_16/mqdefault.jpg', 'SD', 'IPS', 4),
('yt_k4_ips_17', 'Kelas 4 IPS - Perdagangan Indonesia', 'Pembelajaran IPS kelas 4 tentang perdagangan Indonesia', 'https://i.ytimg.com/vi/yt_k4_ips_17/mqdefault.jpg', 'SD', 'IPS', 4),
('yt_k4_ips_18', 'Kelas 4 IPS - Transportasi Indonesia', 'Pembelajaran IPS kelas 4 tentang transportasi Indonesia', 'https://i.ytimg.com/vi/yt_k4_ips_18/mqdefault.jpg', 'SD', 'IPS', 4),
('yt_k4_ips_19', 'Kelas 4 IPS - Pariwisata Indonesia', 'Pembelajaran IPS kelas 4 tentang pariwisata Indonesia', 'https://i.ytimg.com/vi/yt_k4_ips_19/mqdefault.jpg', 'SD', 'IPS', 4),
('yt_k4_ips_20', 'Kelas 4 IPS - Ekonomi Indonesia', 'Pembelajaran IPS kelas 4 tentang ekonomi Indonesia', 'https://i.ytimg.com/vi/yt_k4_ips_20/mqdefault.jpg', 'SD', 'IPS', 4),

-- KELAS 4 Bahasa Indonesia
('yt_k4_bi_01', 'Kelas 4 Bahasa Indonesia - Teks Narasi', 'Pembelajaran Bahasa Indonesia kelas 4 tentang teks narasi', 'https://i.ytimg.com/vi/yt_k4_bi_01/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 4),
('yt_k4_bi_02', 'Kelas 4 Bahasa Indonesia - Teks Deskripsi', 'Pembelajaran Bahasa Indonesia kelas 4 tentang teks deskripsi', 'https://i.ytimg.com/vi/yt_k4_bi_02/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 4),
('yt_k4_bi_03', 'Kelas 4 Bahasa Indonesia - Teks Eksposisi', 'Pembelajaran Bahasa Indonesia kelas 4 tentang teks eksposisi', 'https://i.ytimg.com/vi/yt_k4_bi_03/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 4),
('yt_k4_bi_04', 'Kelas 4 Bahasa Indonesia - Teks Persuasi', 'Pembelajaran Bahasa Indonesia kelas 4 tentang teks persuasi', 'https://i.ytimg.com/vi/yt_k4_bi_04/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 4),
('yt_k4_bi_05', 'Kelas 4 Bahasa Indonesia - Teks Instruksi', 'Pembelajaran Bahasa Indonesia kelas 4 tentang teks instruksi', 'https://i.ytimg.com/vi/yt_k4_bi_05/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 4),
('yt_k4_bi_06', 'Kelas 4 Bahasa Indonesia - Puisi Anak', 'Pembelajaran Bahasa Indonesia kelas 4 tentang puisi anak', 'https://i.ytimg.com/vi/yt_k4_bi_06/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 4),
('yt_k4_bi_07', 'Kelas 4 Bahasa Indonesia - Cerpen', 'Pembelajaran Bahasa Indonesia kelas 4 tentang cerpen', 'https://i.ytimg.com/vi/yt_k4_bi_07/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 4),
('yt_k4_bi_08', 'Kelas 4 Bahasa Indonesia - Drama Anak', 'Pembelajaran Bahasa Indonesia kelas 4 tentang drama anak', 'https://i.ytimg.com/vi/yt_k4_bi_08/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 4),
('yt_k4_bi_09', 'Kelas 4 Bahasa Indonesia - Fabel', 'Pembelajaran Bahasa Indonesia kelas 4 tentang fabel', 'https://i.ytimg.com/vi/yt_k4_bi_09/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 4),
('yt_k4_bi_10', 'Kelas 4 Bahasa Indonesia - Legenda', 'Pembelajaran Bahasa Indonesia kelas 4 tentang legenda', 'https://i.ytimg.com/vi/yt_k4_bi_10/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 4),
('yt_k4_bi_11', 'Kelas 4 Bahasa Indonesia - Dongeng', 'Pembelajaran Bahasa Indonesia kelas 4 tentang dongeng', 'https://i.ytimg.com/vi/yt_k4_bi_11/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 4),
('yt_k4_bi_12', 'Kelas 4 Bahasa Indonesia - Mitos', 'Pembelajaran Bahasa Indonesia kelas 4 tentang mitos', 'https://i.ytimg.com/vi/yt_k4_bi_12/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 4),
('yt_k4_bi_13', 'Kelas 4 Bahasa Indonesia - Antara Fiksi', 'Pembelajaran Bahasa Indonesia kelas 4 tentang antara fiksi', 'https://i.ytimg.com/vi/yt_k4_bi_13/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 4),
('yt_k4_bi_14', 'Kelas 4 Bahasa Indonesia - Buku Anak', 'Pembelajaran Bahasa Indonesia kelas 4 tentang buku anak', 'https://i.ytimg.com/vi/yt_k4_bi_14/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 4),
('yt_k4_bi_15', 'Kelas 4 Bahasa Indonesia - Memoir', 'Pembelajaran Bahasa Indonesia kelas 4 tentang memoir', 'https://i.ytimg.com/vi/yt_k4_bi_15/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 4),
('yt_k4_bi_16', 'Kelas 4 Bahasa Indonesia - Biografi', 'Pembelajaran Bahasa Indonesia kelas 4 tentang biografi', 'https://i.ytimg.com/vi/yt_k4_bi_16/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 4),
('yt_k4_bi_17', 'Kelas 4 Bahasa Indonesia - Buku Saku', 'Pembelajaran Bahasa Indonesia kelas 4 tentang buku saku', 'https://i.ytimg.com/vi/yt_k4_bi_17/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 4),
('yt_k4_bi_18', 'Kelas 4 Bahasa Indonesia - Poster', 'Pembelajaran Bahasa Indonesia kelas 4 tentang poster', 'https://i.ytimg.com/vi/yt_k4_bi_18/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 4),
('yt_k4_bi_19', 'Kelas 4 Bahasa Indonesia - Brosur', 'Pembelajaran Bahasa Indonesia kelas 4 tentang brosur', 'https://i.ytimg.com/vi/yt_k4_bi_19/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 4),
('yt_k4_bi_20', 'Kelas 4 Bahasa Indonesia - Flyer', 'Pembelajaran Bahasa Indonesia kelas 4 tentang flyer', 'https://i.ytimg.com/vi/yt_k4_bi_20/mqdefault.jpg', 'SD', 'Bahasa Indonesia', 4),

-- KELAS 5-6 Bahasa Inggris
('yt_k4_en_01', 'Kelas 4 Bahasa Inggris - Hello', 'Pembelajaran Bahasa Inggris kelas 4 tentang hello', 'https://i.ytimg.com/vi/yt_k4_en_01/mqdefault.jpg', 'SD', 'Bahasa Inggris', 4),
('yt_k4_en_02', 'Kelas 4 Bahasa Inggris - Names', 'Pembelajaran Bahasa Inggris kelas 4 tentang names', 'https://i.ytimg.com/vi/yt_k4_en_02/mqdefault.jpg', 'SD', 'Bahasa Inggris', 4),
('yt_k4_en_03', 'Kelas 4 Bahasa Inggris - Numbers', 'Pembelajaran Bahasa Inggris kelas 4 tentang numbers', 'https://i.ytimg.com/vi/yt_k4_en_03/mqdefault.jpg', 'SD', 'Bahasa Inggris', 4),
('yt_k4_en_04', 'Kelas 4 Bahasa Inggris - Colors', 'Pembelajaran Bahasa Inggris kelas 4 tentang colors', 'https://i.ytimg.com/vi/yt_k4_en_04/mqdefault.jpg', 'SD', 'Bahasa Inggris', 4),
('yt_k4_en_05', 'Kelas 4 Bahasa Inggris - Animals', 'Pembelajaran Bahasa Inggris kelas 4 tentang animals', 'https://i.ytimg.com/vi/yt_k4_en_05/mqdefault.jpg', 'SD', 'Bahasa Inggris', 4),
('yt_k4_en_06', 'Kelas 4 Bahasa Inggris - Family', 'Pembelajaran Bahasa Inggris kelas 4 tentang family', 'https://i.ytimg.com/vi/yt_k4_en_06/mqdefault.jpg', 'SD', 'Bahasa Inggris', 4),
('yt_k4_en_07', 'Kelas 4 Bahasa Inggris - School', 'Pembelajaran Bahasa Inggris kelas 4 tentang school', 'https://i.ytimg.com/vi/yt_k4_en_07/mqdefault.jpg', 'SD', 'Bahasa Inggris', 4),
('yt_k4_en_08', 'Kelas 4 Bahasa Inggris - House', 'Pembelajaran Bahasa Inggris kelas 4 tentang house', 'https://i.ytimg.com/vi/yt_k4_en_08/mqdefault.jpg', 'SD', 'Bahasa Inggris', 4),
('yt_k4_en_09', 'Kelas 4 Bahasa Inggris - Food', 'Pembelajaran Bahasa Inggris kelas 4 tentang food', 'https://i.ytimg.com/vi/yt_k4_en_09/mqdefault.jpg', 'SD', 'Bahasa Inggris', 4),
('yt_k4_en_10', 'Kelas 4 Bahasa Inggris - Drinks', 'Pembelajaran Bahasa Inggris kelas 4 tentang drinks', 'https://i.ytimg.com/vi/yt_k4_en_10/mqdefault.jpg', 'SD', 'Bahasa Inggris', 4),
('yt_k4_en_11', 'Kelas 4 Bahasa Inggris - Toys', 'Pembelajaran Bahasa Inggris kelas 4 tentang toys', 'https://i.ytimg.com/vi/yt_k4_en_11/mqdefault.jpg', 'SD', 'Bahasa Inggris', 4),
('yt_k4_en_12', 'Kelas 4 Bahasa Inggris - Sports', 'Pembelajaran Bahasa Inggris kelas 4 tentang sports', 'https://i.ytimg.com/vi/yt_k4_en_12/mqdefault.jpg', 'SD', 'Bahasa Inggris', 4),
('yt_k4_en_13', 'Kelas 4 Bahasa Inggris - Clothes', 'Pembelajaran Bahasa Inggris kelas 4 tentang clothes', 'https://i.ytimg.com/vi/yt_k4_en_13/mqdefault.jpg', 'SD', 'Bahasa Inggris', 4),
('yt_k4_en_14', 'Kelas 4 Bahasa Inggris - Body Parts', 'Pembelajaran Bahasa Inggris kelas 4 tentang body parts', 'https://i.ytimg.com/vi/yt_k4_en_14/mqdefault.jpg', 'SD', 'Bahasa Inggris', 4),
('yt_k4_en_15', 'Kelas 4 Bahasa Inggris - Weather', 'Pembelajaran Bahasa Inggris kelas 4 tentang weather', 'https://i.ytimg.com/vi/yt_k4_en_15/mqdefault.jpg', 'SD', 'Bahasa Inggris', 4),
('yt_k4_en_16', 'Kelas 4 Bahasa Inggris - Seasons', 'Pembelajaran Bahasa Inggris kelas 4 tentang seasons', 'https://i.ytimg.com/vi/yt_k4_en_16/mqdefault.jpg', 'SD', 'Bahasa Inggris', 4),
('yt_k4_en_17', 'Kelas 4 Bahasa Inggris - Months', 'Pembelajaran Bahasa Inggris kelas 4 tentang months', 'https://i.ytimg.com/vi/yt_k4_en_17/mqdefault.jpg', 'SD', 'Bahasa Inggris', 4),
('yt_k4_en_18', 'Kelas 4 Bahasa Inggris - Days', 'Pembelajaran Bahasa Inggris kelas 4 tentang days', 'https://i.ytimg.com/vi/yt_k4_en_18/mqdefault.jpg', 'SD', 'Bahasa Inggris', 4),
('yt_k4_en_19', 'Kelas 4 Bahasa Inggris - Time', 'Pembelajaran Bahasa Inggris kelas 4 tentang time', 'https://i.ytimg.com/vi/yt_k4_en_19/mqdefault.jpg', 'SD', 'Bahasa Inggris', 4),
('yt_k4_en_20', 'Kelas 4 Bahasa Inggris - Greetings', 'Pembelajaran Bahasa Inggris kelas 4 tentang greetings', 'https://i.ytimg.com/vi/yt_k4_en_20/mqdefault.jpg', 'SD', 'Bahasa Inggris', 4);
