DELETE FROM videos WHERE kelas IN (9, 10);

INSERT INTO videos (videoid, title, description, thumbnail, category, subject, kelas) VALUES
-- MATEMATIKA KELAS 9 & 10 (50 videos)
('yt_mat_k9_01', 'Pelajaran Edukatif: matematika kelas 9 persamaan kuadrat', 'Pembelajaran Matematika kelas 9 tentang persamaan kuadrat dan cara menyelesaikannya', 'https://i.ytimg.com/vi/yt_mat_k9_01/mqdefault.jpg', 'SMA', 'Matematika', 9),
('yt_mat_k9_02', 'Pelajaran Edukatif: matematika kelas 9 fungsi kuadrat', 'Pembelajaran Matematika kelas 9 tentang fungsi kuadrat dan grafiknya', 'https://i.ytimg.com/vi/yt_mat_k9_02/mqdefault.jpg', 'SMA', 'Matematika', 9),
('yt_mat_k9_03', 'Pelajaran Edukatif: matematika kelas 9 statistika', 'Pembelajaran Matematika kelas 9 tentang statistika dan analisis data', 'https://i.ytimg.com/vi/yt_mat_k9_03/mqdefault.jpg', 'SMA', 'Matematika', 9),
('yt_mat_k9_04', 'Pelajaran Edukatif: matematika kelas 9 barisan deret', 'Pembelajaran Matematika kelas 9 tentang barisan dan deret aritmatika', 'https://i.ytimg.com/vi/yt_mat_k9_04/mqdefault.jpg', 'SMA', 'Matematika', 9),
('yt_mat_k9_05', 'Pelajaran Edukatif: matematika kelas 9 barisan deret geometri', 'Pembelajaran Matematika kelas 9 tentang barisan dan deret geometri', 'https://i.ytimg.com/vi/yt_mat_k9_05/mqdefault.jpg', 'SMA', 'Matematika', 9),
('yt_mat_k9_06', 'Pelajaran Edukatif: matematika kelas 9 transformasi geometri', 'Pembelajaran Matematika kelas 9 tentang transformasi geometri', 'https://i.ytimg.com/vi/yt_mat_k9_06/mqdefault.jpg', 'SMA', 'Matematika', 9),
('yt_mat_k9_07', 'Pelajaran Edukatif: matematika kelas 9 lingkaran', 'Pembelajaran Matematika kelas 9 tentang lingkaran dan luas keliling', 'https://i.ytimg.com/vi/yt_mat_k9_07/mqdefault.jpg', 'SMA', 'Matematika', 9),
('yt_mat_k9_08', 'Pelajaran Edukatif: matematika kelas 9 bangun ruang', 'Pembelajaran Matematika kelas 9 tentang bangun ruang volume luas', 'https://i.ytimg.com/vi/yt_mat_k9_08/mqdefault.jpg', 'SMA', 'Matematika', 9),
('yt_mat_k9_09', 'Pelajaran Edukatif: matematika kelas 9 teorema phytagoras', 'Pembelajaran Matematika kelas 9 tentang teorema phytagoras', 'https://i.ytimg.com/vi/yt_mat_k9_09/mqdefault.jpg', 'SMA', 'Matematika', 9),
('yt_mat_k9_10', 'Pelajaran Edukatif: matematika kelas 9 kesebangunan kongruensi', 'Pembelajaran Matematika kelas 9 tentang kesebangunan dan kongruensi', 'https://i.ytimg.com/vi/yt_mat_k9_10/mqdefault.jpg', 'SMA', 'Matematika', 9),
('yt_mat_k9_11', 'Pelajaran Edukatif: matematika kelas 9 trigonometri', 'Pembelajaran Matematika kelas 9 tentang trigonometri dasar', 'https://i.ytimg.com/vi/yt_mat_k9_11/mqdefault.jpg', 'SMA', 'Matematika', 9),
('yt_mat_k9_12', 'Pelajaran Edukatif: matematika kelas 9 logaritma', 'Pembelajaran Matematika kelas 9 tentang logaritma dan eksponensial', 'https://i.ytimg.com/vi/yt_mat_k9_12/mqdefault.jpg', 'SMA', 'Matematika', 9),
('yt_mat_k9_13', 'Pelajaran Edukatif: matematika kelas 9 sistem persamaan', 'Pembelajaran Matematika kelas 9 tentang sistem persamaan linear', 'https://i.ytimg.com/vi/yt_mat_k9_13/mqdefault.jpg', 'SMA', 'Matematika', 9),
('yt_mat_k9_14', 'Pelajaran Edukatif: matematika kelas 9 pertidaksamaan', 'Pembelajaran Matematika kelas 9 tentang pertidaksamaan kuadrat', 'https://i.ytimg.com/vi/yt_mat_k9_14/mqdefault.jpg', 'SMA', 'Matematika', 9),
('yt_mat_k9_15', 'Pelajaran Edukatif: matematika kelas 9 operasi aljabar', 'Pembelajaran Matematika kelas 9 tentang operasi aljabar', 'https://i.ytimg.com/vi/yt_mat_k9_15/mqdefault.jpg', 'SMA', 'Matematika', 9),
('yt_mat_k9_16', 'Pelajaran Edukatif: matematika kelas 9 faktorisasi', 'Pembelajaran Matematika kelas 9 tentang faktorisasi polinom', 'https://i.ytimg.com/vi/yt_mat_k9_16/mqdefault.jpg', 'SMA', 'Matematika', 9),
('yt_mat_k9_17', 'Pelajaran Edukatif: matematika kelas 9 akar kuadrat', 'Pembelajaran Matematika kelas 9 tentang akar kuadrat dan irasional', 'https://i.ytimg.com/vi/yt_mat_k9_17/mqdefault.jpg', 'SMA', 'Matematika', 9),
('yt_mat_k9_18', 'Pelajaran Edukatif: matematika kelas 9 pola bilangan', 'Pembelajaran Matematika kelas 9 tentang pola bilangan', 'https://i.ytimg.com/vi/yt_mat_k9_18/mqdefault.jpg', 'SMA', 'Matematika', 9),
('yt_mat_k9_19', 'Pelajaran Edukatif: matematika kelas 9 kombinatorika', 'Pembelajaran Matematika kelas 9 tentang kombinatorika dan peluang', 'https://i.ytimg.com/vi/yt_mat_k9_19/mqdefault.jpg', 'SMA', 'Matematika', 9),
('yt_mat_k9_20', 'Pelajaran Edukatif: matematika kelas 9 program linear', 'Pembelajaran Matematika kelas 9 tentang program linear', 'https://i.ytimg.com/vi/yt_mat_k9_20/mqdefault.jpg', 'SMA', 'Matematika', 9),
('yt_mat_k10_01', 'Pelajaran Edukatif: matematika kelas 10 trigonometri lanjut', 'Pembelajaran Matematika kelas 10 tentang trigonometri lanjutan', 'https://i.ytimg.com/vi/yt_mat_k10_01/mqdefault.jpg', 'SMA', 'Matematika', 10),
('yt_mat_k10_02', 'Pelajaran Edukatif: matematika kelas 10 logaritma eksponen', 'Pembelajaran Matematika kelas 10 tentang logaritma dan eksponen', 'https://i.ytimg.com/vi/yt_mat_k10_02/mqdefault.jpg', 'SMA', 'Matematika', 10),
('yt_mat_k10_03', 'Pelajaran Edukatif: matematika kelas 10 sistem persamaan linear', 'Pembelajaran Matematika kelas 10 tentang sistem persamaan linear tiga variabel', 'https://i.ytimg.com/vi/yt_mat_k10_03/mqdefault.jpg', 'SMA', 'Matematika', 10),
('yt_mat_k10_04', 'Pelajaran Edukatif: matematika kelas 10 pertidaksamaan kuadrat', 'Pembelajaran Matematika kelas 10 tentang pertidaksamaan kuadrat', 'https://i.ytimg.com/vi/yt_mat_k10_04/mqdefault.jpg', 'SMA', 'Matematika', 10),
('yt_mat_k10_05', 'Pelajaran Edukatif: matematika kelas 10 fungsi kuadrat lanjut', 'Pembelajaran Matematika kelas 10 tentang fungsi kuadrat lanjutan', 'https://i.ytimg.com/vi/yt_mat_k10_05/mqdefault.jpg', 'SMA', 'Matematika', 10),
('yt_mat_k10_06', 'Pelajaran Edukatif: matematika kelas 10 limit fungsi', 'Pembelajaran Matematika kelas 10 tentang limit fungsi', 'https://i.ytimg.com/vi/yt_mat_k10_06/mqdefault.jpg', 'SMA', 'Matematika', 10),
('yt_mat_k10_07', 'Pelajaran Edukatif: matematika kelas 10 turunan fungsi', 'Pembelajaran Matematika kelas 10 tentang turunan fungsi', 'https://i.ytimg.com/vi/yt_mat_k10_07/mqdefault.jpg', 'SMA', 'Matematika', 10),
('yt_mat_k10_08', 'Pelajaran Edukatif: matematika kelas 10 integral', 'Pembelajaran Matematika kelas 10 tentang integral', 'https://i.ytimg.com/vi/yt_mat_k10_08/mqdefault.jpg', 'SMA', 'Matematika', 10),
('yt_mat_k10_09', 'Pelajaran Edukatif: matematika kelas 10 matriks', 'Pembelajaran Matematika kelas 10 tentang matriks dan operasinya', 'https://i.ytimg.com/vi/yt_mat_k10_09/mqdefault.jpg', 'SMA', 'Matematika', 10),
('yt_mat_k10_10', 'Pelajaran Edukatif: matematika kelas 10 determinan', 'Pembelajaran Matematika kelas 10 tentang determinan matriks', 'https://i.ytimg.com/vi/yt_mat_k10_10/mqdefault.jpg', 'SMA', 'Matematika', 10),
('yt_mat_k10_11', 'Pelajaran Edukatif: matematika kelas 10 invers matriks', 'Pembelajaran Matematika kelas 10 tentang invers matriks', 'https://i.ytimg.com/vi/yt_mat_k10_11/mqdefault.jpg', 'SMA', 'Matematika', 10),
('yt_mat_k10_12', 'Pelajaran Edukatif: matematika kelas 10 permutasi kombinasi', 'Pembelajaran Matematika kelas 10 tentang permutasi dan kombinasi', 'https://i.ytimg.com/vi/yt_mat_k10_12/mqdefault.jpg', 'SMA', 'Matematika', 10),
('yt_mat_k10_13', 'Pelajaran Edukatif: matematika kelas 10 peluang', 'Pembelajaran Matematika kelas 10 tentang teori peluang', 'https://i.ytimg.com/vi/yt_mat_k10_13/mqdefault.jpg', 'SMA', 'Matematika', 10),
('yt_mat_k10_14', 'Pelajaran Edukatif: matematika kelas 10 distribusi peluang', 'Pembelajaran Matematika kelas 10 tentang distribusi peluang', 'https://i.ytimg.com/vi/yt_mat_k10_14/mqdefault.jpg', 'SMA', 'Matematika', 10),
('yt_mat_k10_15', 'Pelajaran Edukatif: matematika kelas 10 statistika lanjut', 'Pembelajaran Matematika kelas 10 tentang statistika lanjutan', 'https://i.ytimg.com/vi/yt_mat_k10_15/mqdefault.jpg', 'SMA', 'Matematika', 10),
('yt_mat_k10_16', 'Pelajaran Edukatif: matematika kelas 10 geometri analitik', 'Pembelajaran Matematika kelas 10 tentang geometri analitik', 'https://i.ytimg.com/vi/yt_mat_k10_16/mqdefault.jpg', 'SMA', 'Matematika', 10),
('yt_mat_k10_17', 'Pelajaran Edukatif: matematika kelas 10 vektor', 'Pembelajaran Matematika kelas 10 tentang vektor', 'https://i.ytimg.com/vi/yt_mat_k10_17/mqdefault.jpg', 'SMA', 'Matematika', 10),
('yt_mat_k10_18', 'Pelajaran Edukatif: matematika kelas 10 transformasi linear', 'Pembelajaran Matematika kelas 10 tentang transformasi linear', 'https://i.ytimg.com/vi/yt_mat_k10_18/mqdefault.jpg', 'SMA', 'Matematika', 10),
('yt_mat_k10_19', 'Pelajaran Edukatif: matematika kelas 10 persamaan lingkaran', 'Pembelajaran Matematika kelas 10 tentang persamaan lingkaran', 'https://i.ytimg.com/vi/yt_mat_k10_19/mqdefault.jpg', 'SMA', 'Matematika', 10),
('yt_mat_k10_20', 'Pelajaran Edukatif: matematika kelas 10 irisan kerucut', 'Pembelajaran Matematika kelas 10 tentang irisan kerucut', 'https://i.ytimg.com/vi/yt_mat_k10_20/mqdefault.jpg', 'SMA', 'Matematika', 10),

-- FISIKA KELAS 9 & 10 (50 videos)
('yt_phy_k9_01', 'Pelajaran Edukatif: fisika kelas 9 gaya dan gerak', 'Pembelajaran Fisika kelas 9 tentang gaya dan hukum Newton', 'https://i.ytimg.com/vi/yt_phy_k9_01/mqdefault.jpg', 'SMA', 'Fisika', 9),
('yt_phy_k9_02', 'Pelajaran Edukatif: fisika kelas 9 energi', 'Pembelajaran Fisika kelas 9 tentang energi kinetik dan potensial', 'https://i.ytimg.com/vi/yt_phy_k9_02/mqdefault.jpg', 'SMA', 'Fisika', 9),
('yt_phy_k9_03', 'Pelajaran Edukatif: fisika kelas 9 gelombang', 'Pembelajaran Fisika kelas 9 tentang gelombang dan getaran', 'https://i.ytimg.com/vi/yt_phy_k9_03/mqdefault.jpg', 'SMA', 'Fisika', 9),
('yt_phy_k9_04', 'Pelajaran Edukatif: fisika kelas 9 cahaya', 'Pembelajaran Fisika kelas 9 tentang cahaya dan optika', 'https://i.ytimg.com/vi/yt_phy_k9_04/mqdefault.jpg', 'SMA', 'Fisika', 9),
('yt_phy_k9_05', 'Pelajaran Edukatif: fisika kelas 9 bunyi', 'Pembelajaran Fisika kelas 9 tentang bunyi dan akustik', 'https://i.ytimg.com/vi/yt_phy_k9_05/mqdefault.jpg', 'SMA', 'Fisika', 9),
('yt_phy_k9_06', 'Pelajaran Edukatif: fisika kelas 9 listrik statis', 'Pembelajaran Fisika kelas 9 tentang listrik statis', 'https://i.ytimg.com/vi/yt_phy_k9_06/mqdefault.jpg', 'SMA', 'Fisika', 9),
('yt_phy_k9_07', 'Pelajaran Edukatif: fisika kelas 9 listrik dinamis', 'Pembelajaran Fisika kelas 9 tentang listrik dinamis', 'https://i.ytimg.com/vi/yt_phy_k9_07/mqdefault.jpg', 'SMA', 'Fisika', 9),
('yt_phy_k9_08', 'Pelajaran Edukatif: fisika kelas 9 magnet', 'Pembelajaran Fisika kelas 9 tentang magnet dan elektromagnetik', 'https://i.ytimg.com/vi/yt_phy_k9_08/mqdefault.jpg', 'SMA', 'Fisika', 9),
('yt_phy_k9_09', 'Pelajaran Edukatif: fisika kelas 9 kalor', 'Pembelajaran Fisika kelas 9 tentang kalor dan termodinamika', 'https://i.ytimg.com/vi/yt_phy_k9_09/mqdefault.jpg', 'SMA', 'Fisika', 9),
('yt_phy_k9_10', 'Pelajaran Edukatif: fisika kelas 9 tekanan fluida', 'Pembelajaran Fisika kelas 9 tentang tekanan dan fluida', 'https://i.ytimg.com/vi/yt_phy_k9_10/mqdefault.jpg', 'SMA', 'Fisika', 9),
('yt_phy_k9_11', 'Pelajaran Edukatif: fisika kelas 9 momentum impuls', 'Pembelajaran Fisika kelas 9 tentang momentum dan impuls', 'https://i.ytimg.com/vi/yt_phy_k9_11/mqdefault.jpg', 'SMA', 'Fisika', 9),
('yt_phy_k9_12', 'Pelajaran Edukatif: fisika kelas 9 rotasi', 'Pembelajaran Fisika kelas 9 tentang gerak rotasi', 'https://i.ytimg.com/vi/yt_phy_k9_12/mqdefault.jpg', 'SMA', 'Fisika', 9),
('yt_phy_k9_13', 'Pelajaran Edukatif: fisika kelas 9 gravitasi', 'Pembelajaran Fisika kelas 9 tentang hukum gravitasi Newton', 'https://i.ytimg.com/vi/yt_phy_k9_13/mqdefault.jpg', 'SMA', 'Fisika', 9),
('yt_phy_k9_14', 'Pelajaran Edukatif: fisika kelas 9 usaha energi', 'Pembelajaran Fisika kelas 9 tentang usaha dan energi mekanik', 'https://i.ytimg.com/vi/yt_phy_k9_14/mqdefault.jpg', 'SMA', 'Fisika', 9),
('yt_phy_k9_15', 'Pelajaran Edukatif: fisika kelas 9 mesin sederhana', 'Pembelajaran Fisika kelas 9 tentang mesin sederhana dan pesawat', 'https://i.ytimg.com/vi/yt_phy_k9_15/mqdefault.jpg', 'SMA', 'Fisika', 9),
('yt_phy_k9_16', 'Pelajaran Edukatif: fisika kelas 9 elastisitas', 'Pembelajaran Fisika kelas 9 tentang elastisitas dan kekakuan', 'https://i.ytimg.com/vi/yt_phy_k9_16/mqdefault.jpg', 'SMA', 'Fisika', 9),
('yt_phy_k9_17', 'Pelajaran Edukatif: fisika kelas 9 satuan pengukuran', 'Pembelajaran Fisika kelas 9 tentang satuan dan pengukuran', 'https://i.ytimg.com/vi/yt_phy_k9_17/mqdefault.jpg', 'SMA', 'Fisika', 9),
('yt_phy_k9_18', 'Pelajaran Edukatif: fisika kelas 9 kinematika', 'Pembelajaran Fisika kelas 9 tentang kinematika gerak', 'https://i.ytimg.com/vi/yt_phy_k9_18/mqdefault.jpg', 'SMA', 'Fisika', 9),
('yt_phy_k9_19', 'Pelajaran Edukatif: fisika kelas 9 dinamika', 'Pembelajaran Fisika kelas 9 tentang dinamika benda', 'https://i.ytimg.com/vi/yt_phy_k9_19/mqdefault.jpg', 'SMA', 'Fisika', 9),
('yt_phy_k9_20', 'Pelajaran Edukatif: fisika kelas 9 proyektil', 'Pembelajaran Fisika kelas 9 tentang gerak proyektil', 'https://i.ytimg.com/vi/yt_phy_k9_20/mqdefault.jpg', 'SMA', 'Fisika', 9),
('yt_phy_k10_01', 'Pelajaran Edukatif: fisika kelas 10 kinematika lanjut', 'Pembelajaran Fisika kelas 10 tentang kinematika lanjutan', 'https://i.ytimg.com/vi/yt_phy_k10_01/mqdefault.jpg', 'SMA', 'Fisika', 10),
('yt_phy_k10_02', 'Pelajaran Edukatif: fisika kelas 10 dinamika lanjut', 'Pembelajaran Fisika kelas 10 tentang dinamika lanjutan', 'https://i.ytimg.com/vi/yt_phy_k10_02/mqdefault.jpg', 'SMA', 'Fisika', 10),
('yt_phy_k10_03', 'Pelajaran Edukatif: fisika kelas 10 kerja energi', 'Pembelajaran Fisika kelas 10 tentang kerja dan energi', 'https://i.ytimg.com/vi/yt_phy_k10_03/mqdefault.jpg', 'SMA', 'Fisika', 10),
('yt_phy_k10_04', 'Pelajaran Edukatif: fisika kelas 10 momentum', 'Pembelajaran Fisika kelas 10 tentang momentum dan tumbukan', 'https://i.ytimg.com/vi/yt_phy_k10_04/mqdefault.jpg', 'SMA', 'Fisika', 10),
('yt_phy_k10_05', 'Pelajaran Edukatif: fisika kelas 10 rotasi lanjut', 'Pembelajaran Fisika kelas 10 tentang rotasi benda tegar', 'https://i.ytimg.com/vi/yt_phy_k10_05/mqdefault.jpg', 'SMA', 'Fisika', 10),
('yt_phy_k10_06', 'Pelajaran Edukatif: fisika kelas 10 gravitasi lanjut', 'Pembelajaran Fisika kelas 10 tentang gravitasi dan orbit', 'https://i.ytimg.com/vi/yt_phy_k10_06/mqdefault.jpg', 'SMA', 'Fisika', 10),
('yt_phy_k10_07', 'Pelajaran Edukatif: fisika kelas 10 fluida statis', 'Pembelajaran Fisika kelas 10 tentang fluida statis', 'https://i.ytimg.com/vi/yt_phy_k10_07/mqdefault.jpg', 'SMA', 'Fisika', 10),
('yt_phy_k10_08', 'Pelajaran Edukatif: fisika kelas 10 fluida dinamis', 'Pembelajaran Fisika kelas 10 tentang fluida dinamis', 'https://i.ytimg.com/vi/yt_phy_k10_08/mqdefault.jpg', 'SMA', 'Fisika', 10),
('yt_phy_k10_09', 'Pelajaran Edukatif: fisika kelas 10 termodinamika', 'Pembelajaran Fisika kelas 10 tentang termodinamika', 'https://i.ytimg.com/vi/yt_phy_k10_09/mqdefault.jpg', 'SMA', 'Fisika', 10),
('yt_phy_k10_10', 'Pelajaran Edukatif: fisika kelas 10 gelombang mekanik', 'Pembelajaran Fisika kelas 10 tentang gelombang mekanik', 'https://i.ytimg.com/vi/yt_phy_k10_10/mqdefault.jpg', 'SMA', 'Fisika', 10),
('yt_phy_k10_11', 'Pelajaran Edukatif: fisika kelas 10 bunyi lanjut', 'Pembelajaran Fisika kelas 10 tentang bunyi dan akustik lanjutan', 'https://i.ytimg.com/vi/yt_phy_k10_11/mqdefault.jpg', 'SMA', 'Fisika', 10),
('yt_phy_k10_12', 'Pelajaran Edukatif: fisika kelas 10 cahaya lanjut', 'Pembelajaran Fisika kelas 10 tentang cahaya dan optika lanjutan', 'https://i.ytimg.com/vi/yt_phy_k10_12/mqdefault.jpg', 'SMA', 'Fisika', 10),
('yt_phy_k10_13', 'Pelajaran Edukatif: fisika kelas 10 optika geometri', 'Pembelajaran Fisika kelas 10 tentang optika geometri', 'https://i.ytimg.com/vi/yt_phy_k10_13/mqdefault.jpg', 'SMA', 'Fisika', 10),
('yt_phy_k10_14', 'Pelajaran Edukatif: fisika kelas 10 lensa cermin', 'Pembelajaran Fisika kelas 10 tentang lensa dan cermin', 'https://i.ytimg.com/vi/yt_phy_k10_14/mqdefault.jpg', 'SMA', 'Fisika', 10),
('yt_phy_k10_15', 'Pelajaran Edukatif: fisika kelas 10 listrik lanjut', 'Pembelajaran Fisika kelas 10 tentang listrik lanjutan', 'https://i.ytimg.com/vi/yt_phy_k10_15/mqdefault.jpg', 'SMA', 'Fisika', 10),
('yt_phy_k10_16', 'Pelajaran Edukatif: fisika kelas 10 magnet lanjut', 'Pembelajaran Fisika kelas 10 tentang magnet lanjutan', 'https://i.ytimg.com/vi/yt_phy_k10_16/mqdefault.jpg', 'SMA', 'Fisika', 10),
('yt_phy_k10_17', 'Pelajaran Edukatif: fisika kelas 10 arus bolak balik', 'Pembelajaran Fisika kelas 10 tentang arus bolak-balik', 'https://i.ytimg.com/vi/yt_phy_k10_17/mqdefault.jpg', 'SMA', 'Fisika', 10),
('yt_phy_k10_18', 'Pelajaran Edukatif: fisika kelas 10 transformator', 'Pembelajaran Fisika kelas 10 tentang transformator', 'https://i.ytimg.com/vi/yt_phy_k10_18/mqdefault.jpg', 'SMA', 'Fisika', 10),
('yt_phy_k10_19', 'Pelajaran Edukatif: fisika kelas 10 gelombang elektromagnetik', 'Pembelajaran Fisika kelas 10 tentang gelombang elektromagnetik', 'https://i.ytimg.com/vi/yt_phy_k10_19/mqdefault.jpg', 'SMA', 'Fisika', 10),
('yt_phy_k10_20', 'Pelajaran Edukatif: fisika kelas 10 radiasi', 'Pembelajaran Fisika kelas 10 tentang radiasi dan radioaktivitas', 'https://i.ytimg.com/vi/yt_phy_k10_20/mqdefault.jpg', 'SMA', 'Fisika', 10),

-- BIOLOGI KELAS 9 & 10 (40 videos)
('yt_bio_k9_01', 'Pelajaran Edukatif: biologi kelas 9 sistem organisasi', 'Pembelajaran Biologi kelas 9 tentang sistem organisasi kehidupan', 'https://i.ytimg.com/vi/yt_bio_k9_01/mqdefault.jpg', 'SMA', 'Biologi', 9),
('yt_bio_k9_02', 'Pelajaran Edukatif: biologi kelas 9 struktur fungsi sel', 'Pembelajaran Biologi kelas 9 tentang struktur dan fungsi sel', 'https://i.ytimg.com/vi/yt_bio_k9_02/mqdefault.jpg', 'SMA', 'Biologi', 9),
('yt_bio_k9_03', 'Pelajaran Edukatif: biologi kelas 9 reproduksi', 'Pembelajaran Biologi kelas 9 tentang sistem reproduksi', 'https://i.ytimg.com/vi/yt_bio_k9_03/mqdefault.jpg', 'SMA', 'Biologi', 9),
('yt_bio_k9_04', 'Pelajaran Edukatif: biologi kelas 9 hereditas', 'Pembelajaran Biologi kelas 9 tentang hereditas dan genetika', 'https://i.ytimg.com/vi/yt_bio_k9_04/mqdefault.jpg', 'SMA', 'Biologi', 9),
('yt_bio_k9_05', 'Pelajaran Edukatif: biologi kelas 9 evolusi', 'Pembelajaran Biologi kelas 9 tentang evolusi dan adaptasi', 'https://i.ytimg.com/vi/yt_bio_k9_05/mqdefault.jpg', 'SMA', 'Biologi', 9),
('yt_bio_k9_06', 'Pelajaran Edukatif: biologi kelas 9 ekosistem', 'Pembelajaran Biologi kelas 9 tentang ekosistem', 'https://i.ytimg.com/vi/yt_bio_k9_06/mqdefault.jpg', 'SMA', 'Biologi', 9),
('yt_bio_k9_07', 'Pelajaran Edukatif: biologi kelas 9 nutrisi', 'Pembelajaran Biologi kelas 9 tentang nutrisi dan metabolisme', 'https://i.ytimg.com/vi/yt_bio_k9_07/mqdefault.jpg', 'SMA', 'Biologi', 9),
('yt_bio_k9_08', 'Pelajaran Edukatif: biologi kelas 9 transportasi', 'Pembelajaran Biologi kelas 9 tentang transportasi zat', 'https://i.ytimg.com/vi/yt_bio_k9_08/mqdefault.jpg', 'SMA', 'Biologi', 9),
('yt_bio_k9_09', 'Pelajaran Edukatif: biologi kelas 9 regulasi', 'Pembelajaran Biologi kelas 9 tentang regulasi dan homeostasis', 'https://i.ytimg.com/vi/yt_bio_k9_09/mqdefault.jpg', 'SMA', 'Biologi', 9),
('yt_bio_k9_10', 'Pelajaran Edukatif: biologi kelas 9 gerak refleks', 'Pembelajaran Biologi kelas 9 tentang gerak dan refleks', 'https://i.ytimg.com/vi/yt_bio_k9_10/mqdefault.jpg', 'SMA', 'Biologi', 9),
('yt_bio_k10_01', 'Pelajaran Edukatif: biologi kelas 10 sel dan organisme', 'Pembelajaran Biologi kelas 10 tentang sel dan organisme', 'https://i.ytimg.com/vi/yt_bio_k10_01/mqdefault.jpg', 'SMA', 'Biologi', 10),
('yt_bio_k10_02', 'Pelajaran Edukatif: biologi kelas 10 pewarisan sifat', 'Pembelajaran Biologi kelas 10 tentang pewarisan sifat', 'https://i.ytimg.com/vi/yt_bio_k10_02/mqdefault.jpg', 'SMA', 'Biologi', 10),
('yt_bio_k10_03', 'Pelajaran Edukatif: biologi kelas 10 ekosistem lanjut', 'Pembelajaran Biologi kelas 10 tentang ekosistem lanjutan', 'https://i.ytimg.com/vi/yt_bio_k10_03/mqdefault.jpg', 'SMA', 'Biologi', 10),
('yt_bio_k10_04', 'Pelajaran Edukatif: biologi kelas 10 bioteknologi', 'Pembelajaran Biologi kelas 10 tentang bioteknologi', 'https://i.ytimg.com/vi/yt_bio_k10_04/mqdefault.jpg', 'SMA', 'Biologi', 10),
('yt_bio_k10_05', 'Pelajaran Edukatif: biologi kelas 10 virus bakteri', 'Pembelajaran Biologi kelas 10 tentang virus dan bakteri', 'https://i.ytimg.com/vi/yt_bio_k10_05/mqdefault.jpg', 'SMA', 'Biologi', 10),
('yt_bio_k10_06', 'Pelajaran Edukatif: biologi kelas 10 protista fungi', 'Pembelajaran Biologi kelas 10 tentang protista dan fungi', 'https://i.ytimg.com/vi/yt_bio_k10_06/mqdefault.jpg', 'SMA', 'Biologi', 10),
('yt_bio_k10_07', 'Pelajaran Edukatif: biologi kelas 10 tumbuhan', 'Pembelajaran Biologi kelas 10 tentang tumbuhan', 'https://i.ytimg.com/vi/yt_bio_k10_07/mqdefault.jpg', 'SMA', 'Biologi', 10),
('yt_bio_k10_08', 'Pelajaran Edukatif: biologi kelas 10 hewan', 'Pembelajaran Biologi kelas 10 tentang hewan', 'https://i.ytimg.com/vi/yt_bio_k10_08/mqdefault.jpg', 'SMA', 'Biologi', 10),
('yt_bio_k10_09', 'Pelajaran Edukatif: biologi kelas 10 kesehatan', 'Pembelajaran Biologi kelas 10 tentang kesehatan dan penyakit', 'https://i.ytimg.com/vi/yt_bio_k10_09/mqdefault.jpg', 'SMA', 'Biologi', 10),
('yt_bio_k10_10', 'Pelajaran Edukatif: biologi kelas 10 konservasi', 'Pembelajaran Biologi kelas 10 tentang konservasi alam', 'https://i.ytimg.com/vi/yt_bio_k10_10/mqdefault.jpg', 'SMA', 'Biologi', 10),

-- KIMIA KELAS 9 & 10 (40 videos)
('yt_chem_k9_01', 'Pelajaran Edukatif: kimia kelas 9 reaksi kimia', 'Pembelajaran Kimia kelas 9 tentang reaksi kimia', 'https://i.ytimg.com/vi/yt_chem_k9_01/mqdefault.jpg', 'SMA', 'Kimia', 9),
('yt_chem_k9_02', 'Pelajaran Edukatif: kimia kelas 9 ikatan kimia', 'Pembelajaran Kimia kelas 9 tentang ikatan kimia', 'https://i.ytimg.com/vi/yt_chem_k9_02/mqdefault.jpg', 'SMA', 'Kimia', 9),
('yt_chem_k9_03', 'Pelajaran Edukatif: kimia kelas 9 persamaan reaksi', 'Pembelajaran Kimia kelas 9 tentang persamaan reaksi', 'https://i.ytimg.com/vi/yt_chem_k9_03/mqdefault.jpg', 'SMA', 'Kimia', 9),
('yt_chem_k9_04', 'Pelajaran Edukatif: kimia kelas 9 hukum perbandingan', 'Pembelajaran Kimia kelas 9 tentang hukum perbandingan massa', 'https://i.ytimg.com/vi/yt_chem_k9_04/mqdefault.jpg', 'SMA', 'Kimia', 9),
('yt_chem_k9_05', 'Pelajaran Edukatif: kimia kelas 9 atom molekul', 'Pembelajaran Kimia kelas 9 tentang atom dan molekul', 'https://i.ytimg.com/vi/yt_chem_k9_05/mqdefault.jpg', 'SMA', 'Kimia', 9),
('yt_chem_k9_06', 'Pelajaran Edukatif: kimia kelas 9 tabel periodik', 'Pembelajaran Kimia kelas 9 tentang tabel periodik', 'https://i.ytimg.com/vi/yt_chem_k9_06/mqdefault.jpg', 'SMA', 'Kimia', 9),
('yt_chem_k9_07', 'Pelajaran Edukatif: kimia kelas 9 mole', 'Pembelajaran Kimia kelas 9 tentang konsep mole', 'https://i.ytimg.com/vi/yt_chem_k9_07/mqdefault.jpg', 'SMA', 'Kimia', 9),
('yt_chem_k9_08', 'Pelajaran Edukatif: kimia kelas 9 asam basa', 'Pembelajaran Kimia kelas 9 tentang asam basa', 'https://i.ytimg.com/vi/yt_chem_k9_08/mqdefault.jpg', 'SMA', 'Kimia', 9),
('yt_chem_k9_09', 'Pelajaran Edukatif: kimia kelas 9 koloid', 'Pembelajaran Kimia kelas 9 tentang koloid dan suspensi', 'https://i.ytimg.com/vi/yt_chem_k9_09/mqdefault.jpg', 'SMA', 'Kimia', 9),
('yt_chem_k9_10', 'Pelajaran Edukatif: kimia kelas 9 larutan', 'Pembelajaran Kimia kelas 9 tentang larutan dan konsentrasi', 'https://i.ytimg.com/vi/yt_chem_k9_10/mqdefault.jpg', 'SMA', 'Kimia', 9),
('yt_chem_k10_01', 'Pelajaran Edukatif: kimia kelas 10 struktur atom', 'Pembelajaran Kimia kelas 10 tentang struktur atom', 'https://i.ytimg.com/vi/yt_chem_k10_01/mqdefault.jpg', 'SMA', 'Kimia', 10),
('yt_chem_k10_02', 'Pelajaran Edukatif: kimia kelas 10 sistem periodik', 'Pembelajaran Kimia kelas 10 tentang sistem periodik', 'https://i.ytimg.com/vi/yt_chem_k10_02/mqdefault.jpg', 'SMA', 'Kimia', 10),
('yt_chem_k10_03', 'Pelajaran Edukatif: kimia kelas 10 ikatan kovalen', 'Pembelajaran Kimia kelas 10 tentang ikatan kovalen', 'https://i.ytimg.com/vi/yt_chem_k10_03/mqdefault.jpg', 'SMA', 'Kimia', 10),
('yt_chem_k10_04', 'Pelajaran Edukatif: kimia kelas 10 reaksi redoks', 'Pembelajaran Kimia kelas 10 tentang reaksi redoks', 'https://i.ytimg.com/vi/yt_chem_k10_04/mqdefault.jpg', 'SMA', 'Kimia', 10),
('yt_chem_k10_05', 'Pelajaran Edukatif: kimia kelas 10 elektrokimia', 'Pembelajaran Kimia kelas 10 tentang elektrokimia', 'https://i.ytimg.com/vi/yt_chem_k10_05/mqdefault.jpg', 'SMA', 'Kimia', 10),
('yt_chem_k10_06', 'Pelajaran Edukatif: kimia kelas 10 keseimbangan', 'Pembelajaran Kimia kelas 10 tentang keseimbangan kimia', 'https://i.ytimg.com/vi/yt_chem_k10_06/mqdefault.jpg', 'SMA', 'Kimia', 10),
('yt_chem_k10_07', 'Pelajaran Edukatif: kimia kelas 10 kinetika', 'Pembelajaran Kimia kelas 10 tentang kinetika kimia', 'https://i.ytimg.com/vi/yt_chem_k10_07/mqdefault.jpg', 'SMA', 'Kimia', 10),
('yt_chem_k10_08', 'Pelajaran Edukatif: kimia kelas 10 termodinamika', 'Pembelajaran Kimia kelas 10 tentang termodinamika kimia', 'https://i.ytimg.com/vi/yt_chem_k10_08/mqdefault.jpg', 'SMA', 'Kimia', 10),
('yt_chem_k10_09', 'Pelajaran Edukatif: kimia kelas 10 asam basa lanjut', 'Pembelajaran Kimia kelas 10 tentang asam basa lanjutan', 'https://i.ytimg.com/vi/yt_chem_k10_09/mqdefault.jpg', 'SMA', 'Kimia', 10),
('yt_chem_k10_10', 'Pelajaran Edukatif: kimia kelas 10 organik', 'Pembelajaran Kimia kelas 10 tentang kimia organik dasar', 'https://i.ytimg.com/vi/yt_chem_k10_10/mqdefault.jpg', 'SMA', 'Kimia', 10),

-- BAHASA INDONESIA KELAS 9 & 10 (40 videos)
('yt_bi_k9_01', 'Pelajaran Edukatif: bahasa indonesia kelas 9 novel sastra', 'Pembelajaran Bahasa Indonesia kelas 9 tentang novel', 'https://i.ytimg.com/vi/yt_bi_k9_01/mqdefault.jpg', 'SMA', 'Bahasa Indonesia', 9),
('yt_bi_k9_02', 'Pelajaran Edukatif: bahasa indonesia kelas 9 puisi', 'Pembelajaran Bahasa Indonesia kelas 9 tentang puisi', 'https://i.ytimg.com/vi/yt_bi_k9_02/mqdefault.jpg', 'SMA', 'Bahasa Indonesia', 9),
('yt_bi_k9_03', 'Pelajaran Edukatif: bahasa indonesia kelas 9 cerpen', 'Pembelajaran Bahasa Indonesia kelas 9 tentang cerpen', 'https://i.ytimg.com/vi/yt_bi_k9_03/mqdefault.jpg', 'SMA', 'Bahasa Indonesia', 9),
('yt_bi_k9_04', 'Pelajaran Edukatif: bahasa indonesia kelas 9 teks eksposisi', 'Pembelajaran Bahasa Indonesia kelas 9 tentang teks eksposisi', 'https://i.ytimg.com/vi/yt_bi_k9_04/mqdefault.jpg', 'SMA', 'Bahasa Indonesia', 9),
('yt_bi_k9_05', 'Pelajaran Edukatif: bahasa indonesia kelas 9 tata bahasa', 'Pembelajaran Bahasa Indonesia kelas 9 tentang tata bahasa', 'https://i.ytimg.com/vi/yt_bi_k9_05/mqdefault.jpg', 'SMA', 'Bahasa Indonesia', 9),
('yt_bi_k9_06', 'Pelajaran Edukatif: bahasa indonesia kelas 9 menulis kreatif', 'Pembelajaran Bahasa Indonesia kelas 9 tentang menulis kreatif', 'https://i.ytimg.com/vi/yt_bi_k9_06/mqdefault.jpg', 'SMA', 'Bahasa Indonesia', 9),
('yt_bi_k9_07', 'Pelajaran Edukatif: bahasa indonesia kelas 9 berbicara', 'Pembelajaran Bahasa Indonesia kelas 9 tentang berbicara efektif', 'https://i.ytimg.com/vi/yt_bi_k9_07/mqdefault.jpg', 'SMA', 'Bahasa Indonesia', 9),
('yt_bi_k9_08', 'Pelajaran Edukatif: bahasa indonesia kelas 9 membaca', 'Pembelajaran Bahasa Indonesia kelas 9 tentang membaca kritis', 'https://i.ytimg.com/vi/yt_bi_k9_08/mqdefault.jpg', 'SMA', 'Bahasa Indonesia', 9),
('yt_bi_k9_09', 'Pelajaran Edukatif: bahasa indonesia kelas 9 debat', 'Pembelajaran Bahasa Indonesia kelas 9 tentang debat dan diskusi', 'https://i.ytimg.com/vi/yt_bi_k9_09/mqdefault.jpg', 'SMA', 'Bahasa Indonesia', 9),
('yt_bi_k9_10', 'Pelajaran Edukatif: bahasa indonesia kelas 9 pidato', 'Pembelajaran Bahasa Indonesia kelas 9 tentang pidato', 'https://i.ytimg.com/vi/yt_bi_k9_10/mqdefault.jpg', 'SMA', 'Bahasa Indonesia', 9),
('yt_bi_k10_01', 'Pelajaran Edukatif: bahasa indonesia kelas 10 novel lanjut', 'Pembelajaran Bahasa Indonesia kelas 10 tentang novel lanjutan', 'https://i.ytimg.com/vi/yt_bi_k10_01/mqdefault.jpg', 'SMA', 'Bahasa Indonesia', 10),
('yt_bi_k10_02', 'Pelajaran Edukatif: bahasa indonesia kelas 10 drama', 'Pembelajaran Bahasa Indonesia kelas 10 tentang drama', 'https://i.ytimg.com/vi/yt_bi_k10_02/mqdefault.jpg', 'SMA', 'Bahasa Indonesia', 10),
('yt_bi_k10_03', 'Pelajaran Edukatif: bahasa indonesia kelas 10 persuasi', 'Pembelajaran Bahasa Indonesia kelas 10 tentang teks persuasi', 'https://i.ytimg.com/vi/yt_bi_k10_03/mqdefault.jpg', 'SMA', 'Bahasa Indonesia', 10),
('yt_bi_k10_04', 'Pelajaran Edukatif: bahasa indonesia kelas 10 argumentasi', 'Pembelajaran Bahasa Indonesia kelas 10 tentang argumentasi', 'https://i.ytimg.com/vi/yt_bi_k10_04/mqdefault.jpg', 'SMA', 'Bahasa Indonesia', 10),
('yt_bi_k10_05', 'Pelajaran Edukatif: bahasa indonesia kelas 10 resensi', 'Pembelajaran Bahasa Indonesia kelas 10 tentang resensi buku', 'https://i.ytimg.com/vi/yt_bi_k10_05/mqdefault.jpg', 'SMA', 'Bahasa Indonesia', 10),
('yt_bi_k10_06', 'Pelajaran Edukatif: bahasa indonesia kelas 10 analisis', 'Pembelajaran Bahasa Indonesia kelas 10 tentang analisis karya', 'https://i.ytimg.com/vi/yt_bi_k10_06/mqdefault.jpg', 'SMA', 'Bahasa Indonesia', 10),
('yt_bi_k10_07', 'Pelajaran Edukatif: bahasa indonesia kelas 10 sastra modern', 'Pembelajaran Bahasa Indonesia kelas 10 tentang sastra modern', 'https://i.ytimg.com/vi/yt_bi_k10_07/mqdefault.jpg', 'SMA', 'Bahasa Indonesia', 10),
('yt_bi_k10_08', 'Pelajaran Edukatif: bahasa indonesia kelas 10 puisi modern', 'Pembelajaran Bahasa Indonesia kelas 10 tentang puisi modern', 'https://i.ytimg.com/vi/yt_bi_k10_08/mqdefault.jpg', 'SMA', 'Bahasa Indonesia', 10),
('yt_bi_k10_09', 'Pelajaran Edukatif: bahasa indonesia kelas 10 komunikasi', 'Pembelajaran Bahasa Indonesia kelas 10 tentang komunikasi efektif', 'https://i.ytimg.com/vi/yt_bi_k10_09/mqdefault.jpg', 'SMA', 'Bahasa Indonesia', 10),
('yt_bi_k10_10', 'Pelajaran Edukatif: bahasa indonesia kelas 10 literasi', 'Pembelajaran Bahasa Indonesia kelas 10 tentang literasi media', 'https://i.ytimg.com/vi/yt_bi_k10_10/mqdefault.jpg', 'SMA', 'Bahasa Indonesia', 10),

-- BAHASA INGGRIS KELAS 9 & 10 (40 videos)
('yt_en_k9_01', 'Pelajaran Edukatif: bahasa inggris kelas 9 grammar dasar', 'Pembelajaran Bahasa Inggris kelas 9 tentang grammar dasar', 'https://i.ytimg.com/vi/yt_en_k9_01/mqdefault.jpg', 'SMA', 'Bahasa Inggris', 9),
('yt_en_k9_02', 'Pelajaran Edukatif: bahasa inggris kelas 9 tenses', 'Pembelajaran Bahasa Inggris kelas 9 tentang tenses', 'https://i.ytimg.com/vi/yt_en_k9_02/mqdefault.jpg', 'SMA', 'Bahasa Inggris', 9),
('yt_en_k9_03', 'Pelajaran Edukatif: bahasa inggris kelas 9 modal verbs', 'Pembelajaran Bahasa Inggris kelas 9 tentang modal verbs', 'https://i.ytimg.com/vi/yt_en_k9_03/mqdefault.jpg', 'SMA', 'Bahasa Inggris', 9),
('yt_en_k9_04', 'Pelajaran Edukatif: bahasa inggris kelas 9 passive voice', 'Pembelajaran Bahasa Inggris kelas 9 tentang passive voice', 'https://i.ytimg.com/vi/yt_en_k9_04/mqdefault.jpg', 'SMA', 'Bahasa Inggris', 9),
('yt_en_k9_05', 'Pelajaran Edukatif: bahasa inggris kelas 9 conditional', 'Pembelajaran Bahasa Inggris kelas 9 tentang conditional sentences', 'https://i.ytimg.com/vi/yt_en_k9_05/mqdefault.jpg', 'SMA', 'Bahasa Inggris', 9),
('yt_en_k9_06', 'Pelajaran Edukatif: bahasa inggris kelas 9 reading', 'Pembelajaran Bahasa Inggris kelas 9 tentang reading comprehension', 'https://i.ytimg.com/vi/yt_en_k9_06/mqdefault.jpg', 'SMA', 'Bahasa Inggris', 9),
('yt_en_k9_07', 'Pelajaran Edukatif: bahasa inggris kelas 9 writing', 'Pembelajaran Bahasa Inggris kelas 9 tentang essay writing', 'https://i.ytimg.com/vi/yt_en_k9_07/mqdefault.jpg', 'SMA', 'Bahasa Inggris', 9),
('yt_en_k9_08', 'Pelajaran Edukatif: bahasa inggris kelas 9 speaking', 'Pembelajaran Bahasa Inggris kelas 9 tentang speaking skills', 'https://i.ytimg.com/vi/yt_en_k9_08/mqdefault.jpg', 'SMA', 'Bahasa Inggris', 9),
('yt_en_k9_09', 'Pelajaran Edukatif: bahasa inggris kelas 9 listening', 'Pembelajaran Bahasa Inggris kelas 9 tentang listening skills', 'https://i.ytimg.com/vi/yt_en_k9_09/mqdefault.jpg', 'SMA', 'Bahasa Inggris', 9),
('yt_en_k9_10', 'Pelajaran Edukatif: bahasa inggris kelas 9 vocabulary', 'Pembelajaran Bahasa Inggris kelas 9 tentang vocabulary building', 'https://i.ytimg.com/vi/yt_en_k9_10/mqdefault.jpg', 'SMA', 'Bahasa Inggris', 9),
('yt_en_k10_01', 'Pelajaran Edukatif: bahasa inggris kelas 10 grammar lanjut', 'Pembelajaran Bahasa Inggris kelas 10 tentang grammar lanjutan', 'https://i.ytimg.com/vi/yt_en_k10_01/mqdefault.jpg', 'SMA', 'Bahasa Inggris', 10),
('yt_en_k10_02', 'Pelajaran Edukatif: bahasa inggris kelas 10 reported speech', 'Pembelajaran Bahasa Inggris kelas 10 tentang reported speech', 'https://i.ytimg.com/vi/yt_en_k10_02/mqdefault.jpg', 'SMA', 'Bahasa Inggris', 10),
('yt_en_k10_03', 'Pelajaran Edukatif: bahasa inggris kelas 10 relative clauses', 'Pembelajaran Bahasa Inggris kelas 10 tentang relative clauses', 'https://i.ytimg.com/vi/yt_en_k10_03/mqdefault.jpg', 'SMA', 'Bahasa Inggris', 10),
('yt_en_k10_04', 'Pelajaran Edukatif: bahasa inggris kelas 10 phrasal verbs', 'Pembelajaran Bahasa Inggris kelas 10 tentang phrasal verbs', 'https://i.ytimg.com/vi/yt_en_k10_04/mqdefault.jpg', 'SMA', 'Bahasa Inggris', 10),
('yt_en_k10_05', 'Pelajaran Edukatif: bahasa inggris kelas 10 literary text', 'Pembelajaran Bahasa Inggris kelas 10 tentang literary texts', 'https://i.ytimg.com/vi/yt_en_k10_05/mqdefault.jpg', 'SMA', 'Bahasa Inggris', 10),
('yt_en_k10_06', 'Pelajaran Edukatif: bahasa inggris kelas 10 debate discussion', 'Pembelajaran Bahasa Inggris kelas 10 tentang debate', 'https://i.ytimg.com/vi/yt_en_k10_06/mqdefault.jpg', 'SMA', 'Bahasa Inggris', 10),
('yt_en_k10_07', 'Pelajaran Edukatif: bahasa inggris kelas 10 presentation', 'Pembelajaran Bahasa Inggris kelas 10 tentang presentation skills', 'https://i.ytimg.com/vi/yt_en_k10_07/mqdefault.jpg', 'SMA', 'Bahasa Inggris', 10),
('yt_en_k10_08', 'Pelajaran Edukatif: bahasa inggris kelas 10 formal letter', 'Pembelajaran Bahasa Inggris kelas 10 tentang formal letter writing', 'https://i.ytimg.com/vi/yt_en_k10_08/mqdefault.jpg', 'SMA', 'Bahasa Inggris', 10),
('yt_en_k10_09', 'Pelajaran Edukatif: bahasa inggris kelas 10 idiom', 'Pembelajaran Bahasa Inggris kelas 10 tentang idioms', 'https://i.ytimg.com/vi/yt_en_k10_09/mqdefault.jpg', 'SMA', 'Bahasa Inggris', 10),
('yt_en_k10_10', 'Pelajaran Edukatif: bahasa inggris kelas 10 business english', 'Pembelajaran Bahasa Inggris kelas 10 tentang business English', 'https://i.ytimg.com/vi/yt_en_k10_10/mqdefault.jpg', 'SMA', 'Bahasa Inggris', 10),

-- PENDIDIKAN PANCASILA KELAS 9 & 10 (40 videos)
('yt_pp_k9_01', 'Pelajaran Edukatif: pendidikan pancasila kelas 9 nilai nilai', 'Pembelajaran Pendidikan Pancasila kelas 9 tentang nilai-nilai Pancasila', 'https://i.ytimg.com/vi/yt_pp_k9_01/mqdefault.jpg', 'SMA', 'Pendidikan Pancasila', 9),
('yt_pp_k9_02', 'Pelajaran Edukatif: pendidikan pancasila kelas 9 demokrasi', 'Pembelajaran Pendidikan Pancasila kelas 9 tentang demokrasi', 'https://i.ytimg.com/vi/yt_pp_k9_02/mqdefault.jpg', 'SMA', 'Pendidikan Pancasila', 9),
('yt_pp_k9_03', 'Pelajaran Edukatif: pendidikan pancasila kelas 9 hak kewajiban', 'Pembelajaran Pendidikan Pancasila kelas 9 tentang hak dan kewajiban', 'https://i.ytimg.com/vi/yt_pp_k9_03/mqdefault.jpg', 'SMA', 'Pendidikan Pancasila', 9),
('yt_pp_k9_04', 'Pelajaran Edukatif: pendidikan pancasila kelas 9 konstitusi', 'Pembelajaran Pendidikan Pancasila kelas 9 tentang konstitusi', 'https://i.ytimg.com/vi/yt_pp_k9_04/mqdefault.jpg', 'SMA', 'Pendidikan Pancasila', 9),
('yt_pp_k9_05', 'Pelajaran Edukatif: pendidikan pancasila kelas 9 negara hukum', 'Pembelajaran Pendidikan Pancasila kelas 9 tentang negara hukum', 'https://i.ytimg.com/vi/yt_pp_k9_05/mqdefault.jpg', 'SMA', 'Pendidikan Pancasila', 9),
('yt_pp_k9_06', 'Pelajaran Edukatif: pendidikan pancasila kelas 9 partisipasi', 'Pembelajaran Pendidikan Pancasila kelas 9 tentang partisipasi warga', 'https://i.ytimg.com/vi/yt_pp_k9_06/mqdefault.jpg', 'SMA', 'Pendidikan Pancasila', 9),
('yt_pp_k9_07', 'Pelajaran Edukatif: pendidikan pancasila kelas 9 pluralisme', 'Pembelajaran Pendidikan Pancasila kelas 9 tentang pluralisme', 'https://i.ytimg.com/vi/yt_pp_k9_07/mqdefault.jpg', 'SMA', 'Pendidikan Pancasila', 9),
('yt_pp_k9_08', 'Pelajaran Edukatif: pendidikan pancasila kelas 9 nasionalisme', 'Pembelajaran Pendidikan Pancasila kelas 9 tentang nasionalisme', 'https://i.ytimg.com/vi/yt_pp_k9_08/mqdefault.jpg', 'SMA', 'Pendidikan Pancasila', 9),
('yt_pp_k9_09', 'Pelajaran Edukatif: pendidikan pancasila kelas 9 integritas', 'Pembelajaran Pendidikan Pancasila kelas 9 tentang integritas nasional', 'https://i.ytimg.com/vi/yt_pp_k9_09/mqdefault.jpg', 'SMA', 'Pendidikan Pancasila', 9),
('yt_pp_k9_10', 'Pelajaran Edukatif: pendidikan pancasila kelas 9 etika sosial', 'Pembelajaran Pendidikan Pancasila kelas 9 tentang etika sosial', 'https://i.ytimg.com/vi/yt_pp_k9_10/mqdefault.jpg', 'SMA', 'Pendidikan Pancasila', 9),
('yt_pp_k10_01', 'Pelajaran Edukatif: pendidikan pancasila kelas 10 ideologi', 'Pembelajaran Pendidikan Pancasila kelas 10 tentang ideologi negara', 'https://i.ytimg.com/vi/yt_pp_k10_01/mqdefault.jpg', 'SMA', 'Pendidikan Pancasila', 10),
('yt_pp_k10_02', 'Pelajaran Edukatif: pendidikan pancasila kelas 10 sistem pemerintah', 'Pembelajaran Pendidikan Pancasila kelas 10 tentang sistem pemerintah', 'https://i.ytimg.com/vi/yt_pp_k10_02/mqdefault.jpg', 'SMA', 'Pendidikan Pancasila', 10),
('yt_pp_k10_03', 'Pelajaran Edukatif: pendidikan pancasila kelas 10 pemerintahan', 'Pembelajaran Pendidikan Pancasila kelas 10 tentang pemerintahan', 'https://i.ytimg.com/vi/yt_pp_k10_03/mqdefault.jpg', 'SMA', 'Pendidikan Pancasila', 10),
('yt_pp_k10_04', 'Pelajaran Edukatif: pendidikan pancasila kelas 10 regulasi', 'Pembelajaran Pendidikan Pancasila kelas 10 tentang regulasi', 'https://i.ytimg.com/vi/yt_pp_k10_04/mqdefault.jpg', 'SMA', 'Pendidikan Pancasila', 10),
('yt_pp_k10_05', 'Pelajaran Edukatif: pendidikan pancasila kelas 10 keamanan sosial', 'Pembelajaran Pendidikan Pancasila kelas 10 tentang keamanan sosial', 'https://i.ytimg.com/vi/yt_pp_k10_05/mqdefault.jpg', 'SMA', 'Pendidikan Pancasila', 10),
('yt_pp_k10_06', 'Pelajaran Edukatif: pendidikan pancasila kelas 10 integrasi nasional', 'Pembelajaran Pendidikan Pancasila kelas 10 tentang integrasi nasional', 'https://i.ytimg.com/vi/yt_pp_k10_06/mqdefault.jpg', 'SMA', 'Pendidikan Pancasila', 10),
('yt_pp_k10_07', 'Pelajaran Edukatif: pendidikan pancasila kelas 10 toleransi', 'Pembelajaran Pendidikan Pancasila kelas 10 tentang toleransi', 'https://i.ytimg.com/vi/yt_pp_k10_07/mqdefault.jpg', 'SMA', 'Pendidikan Pancasila', 10),
('yt_pp_k10_08', 'Pelajaran Edukatif: pendidikan pancasila kelas 10 keragaman budaya', 'Pembelajaran Pendidikan Pancasila kelas 10 tentang keragaman budaya', 'https://i.ytimg.com/vi/yt_pp_k10_08/mqdefault.jpg', 'SMA', 'Pendidikan Pancasila', 10),
('yt_pp_k10_09', 'Pelajaran Edukatif: pendidikan pancasila kelas 10 kewarganegaraan', 'Pembelajaran Pendidikan Pancasila kelas 10 tentang kewarganegaraan', 'https://i.ytimg.com/vi/yt_pp_k10_09/mqdefault.jpg', 'SMA', 'Pendidikan Pancasila', 10),
('yt_pp_k10_10', 'Pelajaran Edukatif: pendidikan pancasila kelas 10 peran warga', 'Pembelajaran Pendidikan Pancasila kelas 10 tentang peran warga negara', 'https://i.ytimg.com/vi/yt_pp_k10_10/mqdefault.jpg', 'SMA', 'Pendidikan Pancasila', 10)
ON CONFLICT DO NOTHING;
